canonical: https://simplifier.net/guide/ihs-fhir-r4-ig
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: ihs-fhir-r4-ig
name: IHSFHIRImplementationGuideR4
status: draft
version: 0.1.0
dependencies:
  hl7.fhir.r4.core:
    version: 4.0.1
    uri: http://hl7.org/fhir
    id: hl7_fhir_r4_core
  hl7.fhir.r4.id.core:
    version: 0.1.0
    uri: http://fhir.org/packages/hl7.fhir.r4.id.core/ImplementationGuide/hl7.fhir.r4.id.core
    id: hl7_fhir_r4_id_core
