id: "fhir-ig-anc-satusehat-r4"
canonical: "https://simplifier.net/fhir-ig-anc-satusehat-r4"
name: "FHIR IG ANC Satusehat R4"
title: "FHIR IG ANC Satusehat R4"
description: "FHIR IG for SATUSEHAT Antenatal Care (Draft)"
status: "draft"
version: "0.1.0"
fhirVersion: "4.0.1"
copyrightYear: "2025+"
releaseLabel: "draft"

dependencies:
  hl7.fhir.r4.id.core: 0.1.0

pages:
  index.md:
    title: Home

menu:
  Home: index.html
  Profiles: profiles.html
  Artifacts: artifacts.html