Mapping: script10.6-for-MedicationRequest
Id: script10.6
Title: "Mapping to NCPDP SCRIPT 10.6"
Source: MedicationRequest
Target: "http://ncpdp.org/SCRIPT10_6"
* -> "Message/Body/NewRx"
* identifier -> "Message/Header/PrescriberOrderNumber"
* status -> "no mapping"
* category -> "Message/Body/NewRx/MedicationPrescribed/Directions\r\ror \r\rMessage/Body/NewRx/MedicationPrescribed/StructuredSIG"
* medication[x] -> "Message/Body/NewRx/MedicationPrescribed\r\rMedication.code.coding.code = Message/Body/NewRx/MedicationPrescribed/DrugCoded/ProductCode\r\rMedication.code.coding.system = Message/Body/NewRx/MedicationPrescribed/DrugCoded/ProductCodeQualifier\r\rMedication.code.coding.display = Message/Body/NewRx/MedicationPrescribed/DrugDescription"
* subject -> "Message/Body/NewRx/Patient\r\r(need detail to link to specific patient … Patient.Identification in SCRIPT)"
* encounter -> "no mapping"
* authoredOn -> "Message/Body/NewRx/MedicationPrescribed/WrittenDate"
* reasonCode -> "Message/Body/NewRx/MedicationPrescribed/Diagnosis/Primary/Value"
* reasonReference -> "no mapping"
* note -> "Message/Body/NewRx/MedicationPrescribed/Note"
* dispenseRequest -> "Message/Body/NewRx/MedicationPrescribed/ExpirationDate"
* dispenseRequest.validityPeriod -> "Message/Body/NewRx/MedicationPrescribed/Refills"
* dispenseRequest.numberOfRepeatsAllowed -> "Message/Body/NewRx/MedicationPrescribed/Quantity"
* dispenseRequest.quantity -> "Message/Body/NewRx/MedicationPrescribed/DaysSupply"
* dispenseRequest.expectedSupplyDuration -> "Message/Body/NewRx/MedicationPrescribed/Substitutions"
* substitution -> "specific values within Message/Body/NewRx/MedicationPrescribed/Substitutions"
* substitution.allowed[x] -> "specific values within Message/Body/NewRx/MedicationPrescribed/Substitutions"
* substitution.reason -> "not mapped"
* priorPrescription -> "not mapped"