Resource: ServiceRequest
Id: ServiceRequest
Description: "A record of a request for service such as diagnostic investigations, treatments, or operations to be performed."
* ^meta.lastUpdated = "2025-02-11T05:33:51.9235582+00:00"
* ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Clinical.Care Provision"
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #oo
* ^url = "https://fhir.kemkes.go.id/r4/StructureDefinition/ServiceRequest"
* ^date = "2019-11-01T09:29:23+11:00"
* ^publisher = "Health Level Seven International (Orders and Observations)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/orders/index.cfm"
* obeys prr-1
* . ^short = "A request for a service to be performed"
* . ^definition = "A record of a request for service such as diagnostic investigations, treatments, or operations to be performed."
* . ^alias[0] = "diagnostic request"
* . ^alias[+] = "referral"
* . ^alias[+] = "referral request"
* . ^alias[+] = "transfer of care request"
* identifier 0..0 SU Identifier "Identifiers assigned to this order" "Identifiers assigned to this order instance by the orderer and/or the receiver and/or order fulfiller."
* identifier ^comment = "The identifier.type element is used to distinguish between the identifiers assigned by the orderer (known as the 'Placer' in HL7 v2) and the producer of the observations in response to the order (known as the 'Filler' in HL7 v2).  For further discussion and examples see the resource notes section below."
* instantiatesCanonical 0..0 SU Canonical(http://hl7.org/fhir/StructureDefinition/ActivityDefinition or http://hl7.org/fhir/StructureDefinition/PlanDefinition) "Instantiates FHIR protocol or definition" "The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this ServiceRequest."
* instantiatesCanonical ^comment = "Note: This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number."
* instantiatesUri 0..0 SU uri "Instantiates external protocol or definition" "The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this ServiceRequest."
* instantiatesUri ^comment = "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier."
* basedOn 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/CarePlan or http://hl7.org/fhir/StructureDefinition/ServiceRequest or http://hl7.org/fhir/StructureDefinition/MedicationRequest) "What request fulfills" "Plan/proposal/order fulfilled by this request."
* basedOn ^alias[0] = "fulfills"
* replaces 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/ServiceRequest) "What request replaces" "The request takes the place of the referenced completed or terminated request(s)."
* replaces ^alias[0] = "supersedes"
* replaces ^alias[+] = "prior"
* replaces ^alias[+] = "renewed order"
* requisition 0..1 SU Identifier "Composite Request ID" "A shared identifier common to all service requests that were authorized more or less simultaneously by a single author, representing the composite or group identifier."
* requisition ^comment = "Requests are linked either by a \"basedOn\" relationship (i.e. one request is fulfilling another) or by having a common requisition. Requests that are part of the same requisition are generally treated independently from the perspective of changing their state or maintaining them after initial creation."
* requisition ^requirements = "Some business processes need to know if multiple items were ordered as part of the same \"requisition\" for billing or other purposes."
* requisition ^alias[0] = "grouperId"
* requisition ^alias[+] = "groupIdentifier"
* status 1..1 ?! SU code "draft | active | on-hold | revoked | completed | entered-in-error | unknown" "The status of the order."
* status from http://hl7.org/fhir/ValueSet/request-status|4.0.1 (required)
* status ^comment = "The status is generally fully in the control of the requester - they determine whether the order is draft or active and, after it has been activated, competed, cancelled or suspended. States relating to the activities of the performer are reflected on either the corresponding event (see [Event Pattern](event.html) for general discussion) or using the [Task](task.html) resource."
* status ^isModifierReason = "This element is labeled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "ServiceRequestStatus"
* status ^binding.description = "The status of a service order."
* intent 1..1 ?! SU code "proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | option" "Whether the request is a proposal, plan, an original order or a reflex order."
* intent from http://hl7.org/fhir/ValueSet/request-intent|4.0.1 (required)
* intent ^comment = "This element is labeled as a modifier because the intent alters when and how the resource is actually applicable."
* intent ^isModifierReason = "This element changes the interpretation of all descriptive attributes. For example \"the time the request is recommended to occur\" vs. \"the time the request is authorized to occur\" or \"who is recommended to perform the request\" vs. \"who is authorized to perform the request"
* intent ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* intent ^binding.extension.valueString = "ServiceRequestIntent"
* intent ^binding.description = "The kind of service request."
* category 0..0 SU CodeableConcept "Classification of service" "A code that classifies the service for searching, sorting and display purposes (e.g. \"Surgical Procedure\")."
* category from http://hl7.org/fhir/ValueSet/servicerequest-category (example)
* category ^comment = "There may be multiple axis of categorization depending on the context or use case for retrieving or displaying the resource.  The level of granularity is defined by the category concepts in the value set."
* category ^requirements = "Used for filtering what service request are retrieved and displayed."
* category ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* category ^binding.extension.valueString = "ServiceRequestCategory"
* category ^binding.description = "Classification of the requested service."
* priority 0..1 SU code "routine | urgent | asap | stat" "Indicates how quickly the ServiceRequest should be addressed with respect to other requests."
* priority from http://hl7.org/fhir/ValueSet/request-priority|4.0.1 (required)
* priority ^meaningWhenMissing = "If missing, this task should be performed with normal priority"
* priority ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* priority ^binding.extension.valueString = "ServiceRequestPriority"
* priority ^binding.description = "Identifies the level of importance to be assigned to actioning the request."
* doNotPerform 0..1 ?! SU boolean "True if service/procedure should not be performed" "Set this to true if the record is saying that the service/procedure should NOT be performed."
* doNotPerform ^comment = "In general, only the code and timeframe will be present, though occasional additional qualifiers such as body site or even performer could be included to narrow the scope of the prohibition.  If the ServiceRequest.code and ServiceRequest.doNotPerform both contain negation, that will reinforce prohibition and should not have a double negative interpretation."
* doNotPerform ^requirements = "Used for do not ambulate, do not elevate head of bed, do not flush NG tube, do not take blood pressure on a certain arm, etc."
* doNotPerform ^meaningWhenMissing = "If missing, the request is a positive request e.g. \"do perform\""
* doNotPerform ^isModifierReason = "If true this element negates the specified action. For Example,  instead of a request for a procedure, it is a request for the procedure to not occur."
* code 0..1 SU CodeableConcept "What is being requested/ordered" "A code that identifies a particular service (i.e., procedure, diagnostic investigation, or panel of investigations) that have been requested."
* code from http://hl7.org/fhir/ValueSet/procedure-code (example)
* code ^comment = "Many laboratory and radiology procedure codes embed the specimen/organ system in the test order name, for example,  serum or serum/plasma glucose, or a chest x-ray. The specimen might not be recorded separately from the test code."
* code ^alias[0] = "service requested"
* code ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* code ^binding.extension.valueString = "ServiceRequestCode"
* code ^binding.description = "Codes for tests or services that can be carried out by a designated individual, organization or healthcare service.  For laboratory, LOINC is  (preferred)[http://build.fhir.org/terminologies.html#preferred] and a valueset using LOINC Order codes is available [here](valueset-diagnostic-requests.html)."
* orderDetail 0..0 SU CodeableConcept "Additional order information" "Additional details and instructions about the how the services are to be delivered.   For example, and order for a urinary catheter may have an order detail for an external or indwelling catheter, or an order for a bandage may require additional instructions specifying how the bandage should be applied."
* orderDetail from http://hl7.org/fhir/ValueSet/servicerequest-orderdetail (example)
* orderDetail ^comment = "For information from the medical record intended to support the delivery of the requested services, use the `supportingInformation` element."
* orderDetail ^alias[0] = "detailed instructions"
* orderDetail ^condition = "prr-1"
* orderDetail ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* orderDetail ^binding.extension.valueString = "OrderDetail"
* orderDetail ^binding.description = "Codified order entry details which are based on order context."
* quantity[x] 0..1 SU Quantity or Ratio or Range "Service amount" "An amount of service being requested which can be a quantity ( for example $1,500 home modification), a ratio ( for example, 20 half day visits per month), or a range (2.0 to 1.8 Gy per fraction)."
* quantity[x] ^requirements = "When ordering a service the number of service items may need to be specified separately from the the service item."
* subject 1..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Group or http://hl7.org/fhir/StructureDefinition/Location or http://hl7.org/fhir/StructureDefinition/Device) "Individual or Entity the service is ordered for" "On whom or what the service is to be performed. This is usually a human patient, but can also be requested on animals, groups of humans or animals, devices such as dialysis machines, or even locations (typically for environmental scans)."
* encounter 0..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Encounter) "Encounter in which the request was created" "An encounter that provides additional information about the healthcare context in which this request is made."
* encounter ^alias[0] = "context"
* occurrence[x] 0..1 SU dateTime or Period or Timing "When service should occur" "The date/time at which the requested service should occur."
* occurrence[x] ^alias[0] = "schedule"
* asNeeded[x] 0..1 SU boolean or CodeableConcept "Preconditions for service" "If a CodeableConcept is present, it indicates the pre-condition for performing the service.  For example \"pain\", \"on flare-up\", etc."
* asNeeded[x] from http://hl7.org/fhir/ValueSet/medication-as-needed-reason (example)
* asNeeded[x] ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* asNeeded[x] ^binding.extension.valueString = "ProcedureAsNeededReason"
* asNeeded[x] ^binding.description = "A coded concept identifying the pre-condition that should hold prior to performing a procedure.  For example \"pain\", \"on flare-up\", etc."
* authoredOn 0..1 SU dateTime "Date request signed" "When the request transitioned to being actionable."
* authoredOn ^alias[0] = "orderedOn"
* requester 0..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/PractitionerRole or http://hl7.org/fhir/StructureDefinition/Organization or http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/RelatedPerson or http://hl7.org/fhir/StructureDefinition/Device) "Who/what is requesting service" "The individual who initiated the request and has responsibility for its activation."
* requester ^comment = "This not the dispatcher, but rather who is the authorizer.  This element is not intended to handle delegation which would generally be managed through the Provenance resource."
* requester ^alias[0] = "author"
* requester ^alias[+] = "orderer"
* performerType 0..1 SU CodeableConcept "Performer role" "Desired type of performer for doing the requested service."
* performerType from http://hl7.org/fhir/ValueSet/participant-role (example)
* performerType ^comment = "This is a  role, not  a participation type.  In other words, does not describe the task but describes the capacity.  For example, “compounding pharmacy”, “psychiatrist” or “internal referral”."
* performerType ^alias[0] = "specialty"
* performerType ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* performerType ^binding.extension.valueString = "ServiceRequestParticipantRole"
* performerType ^binding.description = "Indicates specific responsibility of an individual within the care team, such as \"Primary physician\", \"Team coordinator\", \"Caregiver\", etc."
* performer 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/PractitionerRole or http://hl7.org/fhir/StructureDefinition/Organization or http://hl7.org/fhir/StructureDefinition/CareTeam or http://hl7.org/fhir/StructureDefinition/HealthcareService or http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Device or http://hl7.org/fhir/StructureDefinition/RelatedPerson) "Requested performer" "The desired performer for doing the requested service.  For example, the surgeon, dermatopathologist, endoscopist, etc."
* performer ^comment = "If multiple performers are present, it is interpreted as a list of *alternative* performers without any preference regardless of order.  If order of preference is needed use the [request-performerOrder extension](extension-request-performerorder.html).  Use CareTeam to represent a group of performers (for example, Practitioner A *and* Practitioner B)."
* performer ^alias[0] = "request recipient"
* locationCode 0..0 SU CodeableConcept "Requested location" "The preferred location(s) where the procedure should actually happen in coded or free text form. E.g. at home or nursing day care center."
* locationCode from http://terminology.hl7.org/ValueSet/v3-ServiceDeliveryLocationRoleType (example)
* locationCode ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* locationCode ^binding.extension.valueString = "ServiceRequestLocation"
* locationCode ^binding.description = "A location type where services are delivered."
* locationReference 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/Location) "Requested location" "A reference to the the preferred location(s) where the procedure should actually happen. E.g. at home or nursing day care center."
* reasonCode 0..0 SU CodeableConcept "Explanation/Justification for procedure or service" "An explanation or justification for why this service is being requested in coded or textual form.   This is often for billing purposes.  May relate to the resources referred to in `supportingInfo`."
* reasonCode from http://hl7.org/fhir/ValueSet/procedure-reason (example)
* reasonCode ^comment = "This element represents why the referral is being made and may be used to decide how the service will be performed, or even if it will be performed at all.   Use `CodeableConcept.text` element if the data is free (uncoded) text as shown in the [CT Scan example](servicerequest-example-di.html)."
* reasonCode ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* reasonCode ^binding.extension.valueString = "ServiceRequestReason"
* reasonCode ^binding.description = "Diagnosis or problem codes justifying the reason for requesting the service investigation."
* reasonReference 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/Condition or http://hl7.org/fhir/StructureDefinition/Observation or http://hl7.org/fhir/StructureDefinition/DiagnosticReport or http://hl7.org/fhir/StructureDefinition/DocumentReference) "Explanation/Justification for service or service" "Indicates another resource that provides a justification for why this service is being requested.   May relate to the resources referred to in `supportingInfo`."
* reasonReference ^comment = "This element represents why the referral is being made and may be used to decide how the service will be performed, or even if it will be performed at all.    To be as specific as possible,  a reference to  *Observation* or *Condition* should be used if available.  Otherwise when referencing  *DiagnosticReport*  it should contain a finding  in `DiagnosticReport.conclusion` and/or `DiagnosticReport.conclusionCode`.   When using a reference to *DocumentReference*, the target document should contain clear findings language providing the relevant reason for this service request.  Use  the CodeableConcept text element in `ServiceRequest.reasonCode` if the data is free (uncoded) text as shown in the [CT Scan example](servicerequest-example-di.html)."
* insurance 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Coverage or http://hl7.org/fhir/StructureDefinition/ClaimResponse) "Associated insurance coverage" "Insurance plans, coverage extensions, pre-authorizations and/or pre-determinations that may be needed for delivering the requested service."
* supportingInfo 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Resource) "Additional clinical information" "Additional clinical information about the patient or specimen that may influence the services or their interpretations.     This information includes diagnosis, clinical findings and other observations.  In laboratory ordering these are typically referred to as \"ask at order entry questions (AOEs)\".  This includes observations explicitly requested by the producer (filler) to provide context or supporting information needed to complete the order. For example,  reporting the amount of inspired oxygen for blood gas measurements."
* supportingInfo ^comment = "To represent information about how the services are to be delivered use the `instructions` element."
* supportingInfo ^alias[0] = "Ask at order entry question"
* supportingInfo ^alias[+] = "AOE"
* specimen 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/Specimen) "Procedure Samples" "One or more specimens that the laboratory procedure will use."
* specimen ^comment = "Many diagnostic procedures need a specimen, but the request itself is not actually about the specimen. This element is for when the diagnostic is requested on already existing specimens and the request points to the specimen it applies to.    Conversely, if the request is entered first with an unknown specimen, then the [Specimen](specimen.html) resource points to the ServiceRequest."
* bodySite 0..0 SU CodeableConcept "Location on Body" "Anatomic location where the procedure should be performed. This is the target site."
* bodySite from http://hl7.org/fhir/ValueSet/body-site (example)
* bodySite ^comment = "Only used if not implicit in the code found in ServiceRequest.code.  If the use case requires BodySite to be handled as a separate resource instead of an inline coded element (e.g. to identify and track separately)  then use the standard extension [procedure-targetBodyStructure](extension-procedure-targetbodystructure.html)."
* bodySite ^requirements = "Knowing where the procedure is performed is important for tracking if multiple sites are possible."
* bodySite ^alias[0] = "location"
* bodySite ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* bodySite ^binding.extension.valueString = "BodySite"
* bodySite ^binding.description = "Codes describing anatomical locations. May include laterality."
* note 0..0 Annotation "Comments" "Any other notes and comments made about the service request. For example, internal billing notes."
* patientInstruction 0..1 SU string "Patient or consumer-oriented instructions" "Instructions in terms that are understood by the patient or consumer."
* relevantHistory 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Provenance) "Request provenance" "Key events in the history of the request."
* relevantHistory ^comment = "This might not include provenances for all versions of the request – only those deemed “relevant” or important.\rThis SHALL NOT include the Provenance associated with this current version of the resource.  (If that provenance is deemed to be a “relevant” change, it will need to be added as part of a later update.  Until then, it can be queried directly as the Provenance that points to this version using _revinclude\rAll Provenances should have some historical version of this Request as their subject."