Resource: PractitionerRole
Id: PractitionerRole
Description: "A specific set of Roles/Locations/specialties/services that a practitioner may perform at an organization for a period of time."
* ^meta.lastUpdated = "2025-02-11T05:32:43.0938828+00:00"
* ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Base.Individuals"
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #individual
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #pa
* ^url = "https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole"
* ^date = "2019-11-01T09:29:23+11:00"
* ^publisher = "Health Level Seven International (Patient Administration)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/pafm/index.cfm"
* ^purpose = "Need to track services that a healthcare provider is able to provide at an organization's location, and the services that they can perform there."
* . ^short = "Roles/organizations the practitioner is associated with"
* . ^definition = "A specific set of Roles/Locations/specialties/services that a practitioner may perform at an organization for a period of time."
* identifier 0..0 SU Identifier "Business Identifiers that are specific to a role/location" "Business Identifiers that are specific to a role/location."
* identifier ^requirements = "Often, specific identities are assigned for the agent."
* active 0..1 SU boolean "Whether this practitioner role record is in active use" "Whether this practitioner role record is in active use."
* active ^comment = "If this value is false, you may refer to the period to see when the role was in active use. If there is no period specified, no inference can be made about when it was active."
* active ^requirements = "Need to be able to mark a practitioner role record as not to be used because it was created in error, or otherwise no longer in active use."
* active ^meaningWhenMissing = "This resource is generally assumed to be active if no value is provided for the active element"
* period 0..1 SU Period "The period during which the practitioner is authorized to perform in these role(s)" "The period during which the person is authorized to act as a practitioner in these role(s) for the organization."
* period ^requirements = "Even after the agencies is revoked, the fact that it existed must still be recorded."
* practitioner 0..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Practitioner) "Practitioner that is able to provide the defined services for the organization" "Practitioner that is able to provide the defined services for the organization."
* organization 0..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Organization) "Organization where the roles are available" "The organization where the Practitioner performs the roles associated."
* code 0..0 SU CodeableConcept "Roles which this practitioner may perform" "Roles which this practitioner is authorized to perform for the organization."
* code from http://hl7.org/fhir/ValueSet/practitioner-role (example)
* code ^comment = "A person may have more than one role."
* code ^requirements = "Need to know what authority the practitioner has - what can they do?"
* code ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* code ^binding.extension.valueString = "PractitionerRole"
* code ^binding.description = "The role a person plays representing an organization."
* specialty 0..0 SU CodeableConcept "Specific specialty of the practitioner" "Specific specialty of the practitioner."
* specialty from http://hl7.org/fhir/ValueSet/c80-practice-codes (preferred)
* specialty ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* specialty ^binding.extension.valueString = "PractitionerSpecialty"
* specialty ^binding.description = "Specific specialty associated with the agency."
* location 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/Location) "The location(s) at which this practitioner provides care" "The location(s) at which this practitioner provides care."
* healthcareService 0..0 Reference(http://hl7.org/fhir/StructureDefinition/HealthcareService) "The list of healthcare services that this worker provides for this role's Organization/Location(s)" "The list of healthcare services that this worker provides for this role's Organization/Location(s)."
* telecom 0..0 SU ContactPoint "Contact details that are specific to the role/location/service" "Contact details that are specific to the role/location/service."
* telecom ^requirements = "Often practitioners have a dedicated line for each location (or service) that they work at, and need to be able to define separate contact details for each of these."
* availableTime 0..0 BackboneElement "Times the Service Site is available" "A collection of times the practitioner is available or performing this role at the location and/or healthcareservice."
* availableTime ^comment = "More detailed availability information may be provided in associated Schedule/Slot resources."
* availableTime.daysOfWeek 0..0 code "mon | tue | wed | thu | fri | sat | sun" "Indicates which days of the week are available between the start and end Times."
* availableTime.daysOfWeek from http://hl7.org/fhir/ValueSet/days-of-week|4.0.1 (required)
* availableTime.daysOfWeek ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* availableTime.daysOfWeek ^binding.extension.valueString = "DaysOfWeek"
* availableTime.daysOfWeek ^binding.description = "The days of the week."
* availableTime.allDay 0..1 boolean "Always available? e.g. 24 hour service" "Is this always available? (hence times are irrelevant) e.g. 24 hour service."
* availableTime.availableStartTime 0..1 time "Opening time of day (ignored if allDay = true)" "The opening time of day. Note: If the AllDay flag is set, then this time is ignored."
* availableTime.availableStartTime ^comment = "The timezone is expected to be for where this HealthcareService is provided at."
* availableTime.availableEndTime 0..1 time "Closing time of day (ignored if allDay = true)" "The closing time of day. Note: If the AllDay flag is set, then this time is ignored."
* availableTime.availableEndTime ^comment = "The timezone is expected to be for where this HealthcareService is provided at."
* notAvailable 0..0 BackboneElement "Not available during this time due to provided reason" "The practitioner is not available or performing this role during this period of time due to the provided reason."
* notAvailable.description 1..1 string "Reason presented to the user explaining why time not available" "The reason that can be presented to the user as to why this time is not available."
* notAvailable.during 0..1 Period "Service not available from this date" "Service is not available (seasonally or for a public holiday) from this date."
* availabilityExceptions 0..1 string "Description of availability exceptions" "A description of site availability exceptions, e.g. public holiday availability. Succinctly describing all possible exceptions to normal site availability as details in the available Times and not available Times."
* endpoint 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Endpoint) "Technical endpoints providing access to services operated for the practitioner with this role" "Technical endpoints providing access to services operated for the practitioner with this role."
* endpoint ^requirements = "Organizations have multiple systems that provide various services and ,ay also be different for practitioners too.\r\rSo the endpoint satisfies the need to be able to define the technical connection details for how to connect to them, and for what purpose."