Resource: Device
Id: Device
Description: "A type of a manufactured item that is used in the provision of healthcare without being substantially changed through that activity. The device may be a medical or non-medical device."
* ^meta.lastUpdated = "2025-02-11T05:21:42.7168193+00:00"
* ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Base.Entities"
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #business
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #oo
* ^url = "https://fhir.kemkes.go.id/r4/StructureDefinition/Device"
* ^status = #draft
* ^date = "2019-11-01T09:29:23+11:00"
* ^publisher = "Health Level Seven International (Orders and Observations)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/orders/index.cfm"
* ^purpose = "Allows institutions to track their devices."
* . ^short = "Item used in healthcare"
* . ^definition = "A type of a manufactured item that is used in the provision of healthcare without being substantially changed through that activity. The device may be a medical or non-medical device."
* identifier 0..0 Identifier "Instance identifier" "Unique instance identifiers assigned to a device by manufacturers other organizations or owners."
* identifier ^comment = "The barcode string from a barcode present on a device label or package may identify the instance, include names given to the device in local usage, or may identify the type of device. If the identifier identifies the type of device, Device.type element should be used."
* definition 0..1 Reference(http://hl7.org/fhir/StructureDefinition/DeviceDefinition) "The reference to the definition for the device" "The reference to the definition for the device."
* udiCarrier 0..0 SU BackboneElement "Unique Device Identifier (UDI) Barcode string" "Unique device identifier (UDI) assigned to device label or package.  Note that the Device may include multiple udiCarriers as it either may include just the udiCarrier for the jurisdiction it is sold, or for multiple jurisdictions it could have been sold."
* udiCarrier ^comment = "UDI may identify an unique instance of a device, or it may only identify the type of the device.  See [UDI mappings](device-mappings.html#udi) for a complete mapping of UDI parts to Device."
* udiCarrier.deviceIdentifier 0..1 SU string "Mandatory fixed portion of UDI" "The device identifier (DI) is a mandatory, fixed portion of a UDI that identifies the labeler and the specific version or model of a device."
* udiCarrier.deviceIdentifier ^alias = "DI"
* udiCarrier.issuer 0..1 uri "UDI Issuing Organization" "Organization that is charged with issuing UDIs for devices.  For example, the US FDA issuers include :\n1) GS1: \nhttp://hl7.org/fhir/NamingSystem/gs1-di, \n2) HIBCC:\nhttp://hl7.org/fhir/NamingSystem/hibcc-dI, \n3) ICCBBA for blood containers:\nhttp://hl7.org/fhir/NamingSystem/iccbba-blood-di, \n4) ICCBA for other devices:\nhttp://hl7.org/fhir/NamingSystem/iccbba-other-di."
* udiCarrier.issuer ^alias = "Barcode System"
* udiCarrier.jurisdiction 0..1 uri "Regional UDI authority" "The identity of the authoritative source for UDI generation within a  jurisdiction.  All UDIs are globally unique within a single namespace with the appropriate repository uri as the system.  For example,  UDIs of devices managed in the U.S. by the FDA, the value is  http://hl7.org/fhir/NamingSystem/fda-udi."
* udiCarrier.jurisdiction ^requirements = "Allows a recipient of a UDI to know which database will contain the UDI-associated metadata."
* udiCarrier.carrierAIDC 0..1 SU base64Binary "UDI Machine Readable Barcode String" "The full UDI carrier of the Automatic Identification and Data Capture (AIDC) technology representation of the barcode string as printed on the packaging of the device - e.g., a barcode or RFID.   Because of limitations on character sets in XML and the need to round-trip JSON data through XML, AIDC Formats *SHALL* be base64 encoded."
* udiCarrier.carrierAIDC ^comment = "The AIDC form of UDIs should be scanned or otherwise used for the identification of the device whenever possible to minimize errors in records resulting from manual transcriptions. If separate barcodes for DI and PI are present, concatenate the string with DI first and in order of human readable expression on label."
* udiCarrier.carrierAIDC ^alias = "Automatic Identification and Data Capture"
* udiCarrier.carrierHRF 0..1 SU string "UDI Human Readable Barcode String" "The full UDI carrier as the human readable form (HRF) representation of the barcode string as printed on the packaging of the device."
* udiCarrier.carrierHRF ^comment = "If separate barcodes for DI and PI are present, concatenate the string with DI first and in order of human readable expression on label."
* udiCarrier.carrierHRF ^alias = "Human Readable Form"
* udiCarrier.entryType 0..1 code "barcode | rfid | manual +" "A coded entry to indicate how the data was entered."
* udiCarrier.entryType from http://hl7.org/fhir/ValueSet/udi-entry-type|4.0.1 (required)
* udiCarrier.entryType ^requirements = "Supports a way to distinguish hand entered from machine read data."
* udiCarrier.entryType ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* udiCarrier.entryType ^binding.extension.valueString = "UDIEntryType"
* udiCarrier.entryType ^binding.description = "Codes to identify how UDI data was entered."
* status 0..1 ?! SU code "active | inactive | entered-in-error | unknown" "Status of the Device availability."
* status from http://hl7.org/fhir/ValueSet/device-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains the codes inactive and entered-in-error that mark the device (record)as not currently valid."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "FHIRDeviceStatus"
* status ^binding.description = "The availability status of the device."
* statusReason 0..0 CodeableConcept "online | paused | standby | offline | not-ready | transduc-discon | hw-discon | off" "Reason for the dtatus of the Device availability."
* statusReason from http://hl7.org/fhir/ValueSet/device-status-reason (extensible)
* statusReason ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* statusReason ^binding.extension.valueString = "FHIRDeviceStatusReason"
* statusReason ^binding.description = "The availability status reason of the device."
* distinctIdentifier 0..1 string "The distinct identification string" "The distinct identification string as required by regulation for a human cell, tissue, or cellular and tissue-based product."
* distinctIdentifier ^comment = "For example, this applies to devices in the United States regulated under *Code of Federal Regulation 21CFR§1271.290(c)*."
* distinctIdentifier ^alias = "Distinct Identification Code (DIC)"
* manufacturer 0..1 string "Name of device manufacturer" "A name of the manufacturer."
* manufactureDate 0..1 dateTime "Date when the device was made" "The date and time when the device was manufactured."
* expirationDate 0..1 dateTime "Date and time of expiry of this device (if applicable)" "The date and time beyond which this device is no longer valid or should not be used (if applicable)."
* lotNumber 0..1 string "Lot number of manufacture" "Lot number assigned by the manufacturer."
* serialNumber 0..1 string "Serial number assigned by the manufacturer" "The serial number assigned by the organization when the device was manufactured."
* serialNumber ^comment = "Alphanumeric Maximum 20."
* deviceName 0..0 BackboneElement "The name of the device as given by the manufacturer" "This represents the manufacturer's name of the device as provided by the device, from a UDI label, or by a person describing the Device.  This typically would be used when a person provides the name(s) or when the device represents one of the names available from DeviceDefinition."
* deviceName.name 1..1 string "The name of the device" "The name of the device."
* deviceName.name ^alias = "Σ"
* deviceName.type 1..1 code "udi-label-name | user-friendly-name | patient-reported-name | manufacturer-name | model-name | other" "The type of deviceName.\nUDILabelName | UserFriendlyName | PatientReportedName | ManufactureDeviceName | ModelName."
* deviceName.type from http://hl7.org/fhir/ValueSet/device-nametype|4.0.1 (required)
* deviceName.type ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* deviceName.type ^binding.extension.valueString = "DeviceNameType"
* deviceName.type ^binding.description = "The type of name the device is referred by."
* modelNumber 0..1 string "The model number for the device" "The model number for the device."
* partNumber 0..1 string "The part number of the device" "The part number of the device."
* partNumber ^comment = "Alphanumeric Maximum 20."
* type 0..1 CodeableConcept "The kind or type of device" "The kind or type of device."
* type from http://hl7.org/fhir/ValueSet/device-type (example)
* type ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* type ^binding.extension.valueString = "DeviceType"
* type ^binding.description = "Codes to identify medical devices."
* specialization 0..0 BackboneElement "The capabilities supported on a  device, the standards to which the device conforms for a particular purpose, and used for the communication" "The capabilities supported on a  device, the standards to which the device conforms for a particular purpose, and used for the communication."
* specialization.systemType 1..1 CodeableConcept "The standard that is used to operate and communicate" "The standard that is used to operate and communicate."
* specialization.systemType ^alias = "Σ"
* specialization.version 0..1 string "The version of the standard that is used to operate and communicate" "The version of the standard that is used to operate and communicate."
* version 0..0 BackboneElement "The actual design of the device or software version running on the device" "The actual design of the device or software version running on the device."
* version.type 0..1 CodeableConcept "The type of the device version" "The type of the device version."
* version.type ^alias = "Σ"
* version.component 0..1 Identifier "A single component of the device version" "A single component of the device version."
* version.value 1..1 string "The version text" "The version text."
* property 0..0 BackboneElement "The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties" "The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties."
* property.type 1..1 CodeableConcept "Code that specifies the property DeviceDefinitionPropetyCode (Extensible)" "Code that specifies the property DeviceDefinitionPropetyCode (Extensible)."
* property.valueQuantity 0..0 Quantity "Property value as a quantity" "Property value as a quantity."
* property.valueCode 0..0 CodeableConcept "Property value as a code, e.g., NTP4 (synced to NTP)" "Property value as a code, e.g., NTP4 (synced to NTP)."
* patient 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Patient) "Patient to whom Device is affixed" "Patient information, If the device is affixed to a person."
* patient ^requirements = "If the device is implanted in a patient, then need to associate the device to the patient."
* owner 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Organization) "Organization responsible for device" "An organization that is responsible for the provision and ongoing maintenance of the device."
* contact 0..0 ContactPoint "Details for human/organization for support" "Contact details for an organization or a particular human that is responsible for the device."
* contact ^comment = "used for troubleshooting etc."
* location 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Location) "Where the device is found" "The place where the device can be found."
* location ^requirements = "Device.location can be used to track device location."
* url 0..1 uri "Network address to contact device" "A network address on which the device may be contacted directly."
* url ^comment = "If the device is running a FHIR server, the network address should  be the Base URL from which a conformance statement may be retrieved."
* note 0..0 Annotation "Device notes and comments" "Descriptive information, usage information or implantation information that is not captured in an existing element."
* safety 0..0 SU CodeableConcept "Safety Characteristics of Device" "Provides additional safety characteristics about a medical device.  For example devices containing latex."
* parent 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Device) "The parent device" "The parent device."