Resource: MedicationDispense
Id: MedicationDispense
Description: "Indicates that a medication product is to be or has been dispensed for a named person/patient.  This includes a description of the medication product (supply) provided and the instructions for administering the medication.  The medication dispense is the result of a pharmacy system responding to a medication order."
* ^meta.lastUpdated = "2025-02-11T05:36:18.4486635+00:00"
* ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Clinical.Medications"
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #phx
* ^url = "https://fhir.kemkes.go.id/r4/StructureDefinition/MedicationDispense"
* ^date = "2019-11-01T09:29:23+11:00"
* ^publisher = "Health Level Seven International (Pharmacy)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/medication/index.cfm"
* obeys mdd-1
* . ^short = "Dispensing a medication to a named patient"
* . ^definition = "Indicates that a medication product is to be or has been dispensed for a named person/patient.  This includes a description of the medication product (supply) provided and the instructions for administering the medication.  The medication dispense is the result of a pharmacy system responding to a medication order."
* identifier 0..0 Identifier "External identifier" "Identifiers associated with this Medication Dispense that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate. They are business identifiers assigned to this resource by the performer or other systems and remain constant as the resource is updated and propagates from server to server."
* identifier ^comment = "This is a business identifier, not a resource identifier."
* partOf 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Procedure) "Event that dispense is part of" "The procedure that trigger the dispense."
* status 1..1 ?! SU code "preparation | in-progress | cancelled | on-hold | completed | entered-in-error | stopped | declined | unknown" "A code specifying the state of the set of dispense events."
* status from http://hl7.org/fhir/ValueSet/medicationdispense-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "MedicationDispenseStatus"
* status ^binding.description = "A coded concept specifying the state of the dispense event."
* statusReason[x] 0..1 CodeableConcept or Reference(http://hl7.org/fhir/StructureDefinition/DetectedIssue) "Why a dispense was not performed" "Indicates the reason why a dispense was not performed."
* statusReason[x] from http://hl7.org/fhir/ValueSet/medicationdispense-status-reason (example)
* statusReason[x] ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* statusReason[x] ^binding.extension.valueString = "MedicationDispenseStatusReason"
* statusReason[x] ^binding.description = "A code describing why a dispense was not performed."
* category 0..1 CodeableConcept "Type of medication dispense" "Indicates the type of medication dispense (for example, where the medication is expected to be consumed or administered (i.e. inpatient or outpatient))."
* category from http://hl7.org/fhir/ValueSet/medicationdispense-category (preferred)
* category ^comment = "The category can be used to include where the medication is expected to be consumed or other types of dispenses.  Invariants can be used to bind to different value sets when profiling to bind."
* category ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* category ^binding.extension.valueString = "MedicationDispenseCategory"
* category ^binding.description = "A code describing where the dispensed medication is expected to be consumed or administered."
* medication[x] 1..1 SU CodeableConcept or Reference(http://hl7.org/fhir/StructureDefinition/Medication) "What medication was supplied" "Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications."
* medication[x] from http://hl7.org/fhir/ValueSet/medication-codes (example)
* medication[x] ^comment = "If only a code is specified, then it needs to be a code for a specific product. If more information is required, then the use of the medication resource is recommended.  For example, if you require form or lot number, then you must reference the Medication resource."
* medication[x] ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* medication[x] ^binding.extension.valueString = "MedicationCode"
* medication[x] ^binding.description = "A coded concept identifying which substance or product can be dispensed."
* subject 0..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Group) "Who the dispense is for" "A link to a resource representing the person or the group to whom the medication will be given."
* subject ^comment = "SubstanceAdministration->subject->Patient."
* context 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Encounter or http://hl7.org/fhir/StructureDefinition/EpisodeOfCare) "Encounter / Episode associated with event" "The encounter or episode of care that establishes the context for this event."
* supportingInformation 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Resource) "Information that supports the dispensing of the medication" "Additional information that supports the medication being dispensed."
* performer 0..0 BackboneElement "Who performed event" "Indicates who or what performed the event."
* performer.function 0..1 CodeableConcept "Who performed the dispense and what they did" "Distinguishes the type of performer in the dispense.  For example, date enterer, packager, final checker."
* performer.function from http://hl7.org/fhir/ValueSet/medicationdispense-performer-function (example)
* performer.function ^requirements = "Allows disambiguation of the types of involvement of different performers."
* performer.function ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* performer.function ^binding.extension.valueString = "MedicationDispensePerformerFunction"
* performer.function ^binding.description = "A code describing the role an individual played in dispensing a medication."
* performer.actor 1..1 Reference(http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/PractitionerRole or http://hl7.org/fhir/StructureDefinition/Organization or http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Device or http://hl7.org/fhir/StructureDefinition/RelatedPerson) "Individual who was performing" "The device, practitioner, etc. who performed the action.  It should be assumed that the actor is the dispenser of the medication."
* location 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Location) "Where the dispense occurred" "The principal physical location where the dispense was performed."
* authorizingPrescription 0..0 Reference(http://hl7.org/fhir/StructureDefinition/MedicationRequest) "Medication order that authorizes the dispense" "Indicates the medication order that is being dispensed against."
* authorizingPrescription ^comment = "Maps to basedOn in Event logical model."
* type 0..1 CodeableConcept "Trial fill, partial fill, emergency fill, etc." "Indicates the type of dispensing event that is performed. For example, Trial Fill, Completion of Trial, Partial Fill, Emergency Fill, Samples, etc."
* type from http://terminology.hl7.org/ValueSet/v3-ActPharmacySupplyType (example)
* type ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* type ^binding.extension.valueString = "MedicationDispenseType"
* type ^binding.description = "Indicates the type of dispensing event that is performed. For example, Trial Fill, Completion of Trial, Partial Fill, Emergency Fill, Samples, etc."
* quantity 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Amount dispensed" "The amount of medication that has been dispensed. Includes unit of measure."
* daysSupply 0..1 http://hl7.org/fhir/StructureDefinition/SimpleQuantity "Amount of medication expressed as a timing amount" "The amount of medication expressed as a timing amount."
* whenPrepared 0..1 SU dateTime "When product was packaged and reviewed" "The time when the dispensed product was packaged and reviewed."
* whenHandedOver 0..1 dateTime "When product was given out" "The time the dispensed product was provided to the patient or their representative."
* destination 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Location) "Where the medication was sent" "Identification of the facility/location where the medication was shipped to, as part of the dispense event."
* receiver 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Practitioner) "Who collected the medication" "Identifies the person who picked up the medication.  This will usually be a patient or their caregiver, but some cases exist where it can be a healthcare professional."
* note 0..0 Annotation "Information about the dispense" "Extra information about the dispense that could not be conveyed in the other attributes."
* dosageInstruction 0..0 Dosage "How the medication is to be used by the patient or administered by the caregiver" "Indicates how the medication is to be used by the patient."
* dosageInstruction ^comment = "When the dose or rate is intended to change over the entire administration period (e.g. Tapering dose prescriptions), multiple instances of dosage instructions will need to be supplied to convey the different doses/rates.\rThe pharmacist reviews the medication order prior to dispense and updates the dosageInstruction based on the actual product being dispensed."
* substitution 0..1 BackboneElement "Whether a substitution was performed on the dispense" "Indicates whether or not substitution was made as part of the dispense.  In some cases, substitution will be expected but does not happen, in other cases substitution is not expected but does happen.  This block explains what substitution did or did not happen and why.  If nothing is specified, substitution was not done."
* substitution.wasSubstituted 1..1 boolean "Whether a substitution was or was not performed on the dispense" "True if the dispenser dispensed a different drug or product from what was prescribed."
* substitution.type 0..1 CodeableConcept "Code signifying whether a different drug was dispensed from what was prescribed" "A code signifying whether a different drug was dispensed from what was prescribed."
* substitution.type from http://terminology.hl7.org/ValueSet/v3-ActSubstanceAdminSubstitutionCode (example)
* substitution.type ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* substitution.type ^binding.extension.valueString = "MedicationIntendedSubstitutionType"
* substitution.type ^binding.description = "A coded concept describing whether a different medicinal product may be dispensed other than the product as specified exactly in the prescription."
* substitution.reason 0..0 CodeableConcept "Why was substitution made" "Indicates the reason for the substitution (or lack of substitution) from what was prescribed."
* substitution.reason from http://terminology.hl7.org/ValueSet/v3-SubstanceAdminSubstitutionReason (example)
* substitution.reason ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* substitution.reason ^binding.extension.valueString = "MedicationIntendedSubstitutionReason"
* substitution.reason ^binding.description = "A coded concept describing the reason that a different medication should (or should not) be substituted from what was prescribed."
* substitution.responsibleParty 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/PractitionerRole) "Who is responsible for the substitution" "The person or organization that has primary responsibility for the substitution."
* detectedIssue 0..0 Reference(http://hl7.org/fhir/StructureDefinition/DetectedIssue) "Clinical issue with action" "Indicates an actual or potential clinical issue with or between one or more active or proposed clinical actions for a patient; e.g. drug-drug interaction, duplicate therapy, dosage alert etc."
* detectedIssue ^comment = "This element can include a detected issue that has been identified either by a decision support system or by a clinician and may include information on the steps that were taken to address the issue."
* detectedIssue ^alias[0] = "Contraindication"
* detectedIssue ^alias[+] = "Drug Utilization Review (DUR)"
* detectedIssue ^alias[+] = "Alert"
* eventHistory 0..0 Reference(http://hl7.org/fhir/StructureDefinition/Provenance) "A list of relevant lifecycle events" "A summary of the events of interest that have occurred, such as when the dispense was verified."
* eventHistory ^comment = "This might not include provenances for all versions of the request – only those deemed “relevant” or important. This SHALL NOT include the Provenance associated with this current version of the resource. (If that provenance is deemed to be a “relevant” change, it will need to be added as part of a later update. Until then, it can be queried directly as the Provenance that points to this version using _revinclude All Provenances should have some historical version of this Request as their subject.)."