Resource: Bundle
Parent: Resource
Id: Bundle
Description: "A container for a collection of resources."
* ^meta.lastUpdated = "2025-02-11T05:41:51.067876+00:00"
* ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Foundation.Other"
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #normative
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-normative-version"
* ^extension[=].valueCode = #4.0.0
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 5
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #not-classified
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #fhir
* ^url = "https://fhir.kemkes.go.id/r4/StructureDefinition/Bundle"
* ^date = "2021-12-31T11:10:15.2517326+00:00"
* ^publisher = "Health Level Seven International (FHIR Infrastructure)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/fiwg/index.cfm"
* . ^short = "Contains a collection of resources"
* . ^definition = "A container for a collection of resources."
* identifier 0..1 SU Identifier "Persistent identifier for the bundle" "A persistent identifier for the bundle that won't change as a bundle is copied from server to server."
* identifier ^comment = "Persistent identity generally only matters for batches of type Document, Message, and Collection. It would not normally be populated for search and history results and servers ignore Bundle.identifier when processing batches and transactions. For Documents  the .identifier SHALL be populated such that the .identifier is globally unique."
* type 1..1 SU code "document | message | transaction | transaction-response | batch | batch-response | history | searchset | collection" "Indicates the purpose of this bundle - how it is intended to be used."
* type from http://hl7.org/fhir/ValueSet/bundle-type|4.0.1 (required)
* type ^comment = "It's possible to use a bundle for other purposes (e.g. a document can be accepted as a transaction). This is primarily defined so that there can be specific rules for some of the bundle types."
* type ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* type ^binding.extension.valueString = "BundleType"
* type ^binding.description = "Indicates the purpose of a bundle - how it is intended to be used."
* timestamp 0..1 SU instant "When the bundle was assembled" "The date/time that the bundle was assembled - i.e. when the resources were placed in the bundle."
* timestamp ^comment = "For many bundles, the timestamp is equal to .meta.lastUpdated, because they are not stored (e.g. search results). When a bundle is placed in a persistent store, .meta.lastUpdated will be usually be changed by the server. When the bundle is a message, a middleware agent altering the message (even if not stored) SHOULD update .meta.lastUpdated. .timestamp is used to track the original time of the Bundle, and SHOULD be populated.  \n\nUsage:\n\n* document : the date the document was created. Note: the composition may predate the document, or be associated with multiple documents. The date of the composition - the authoring time - may be earlier than the document assembly time\n* message : the date that the content of the message was assembled. This date is not changed by middleware engines unless they add additional data that changes the meaning of the time of the message\n* history : the date that the history was assembled. This time would be used as the _since time to ask for subsequent updates\n* searchset : the time that the search set was assembled. Note that different pages MAY have different timestamps but need not. Having different timestamps does not imply that subsequent pages will represent or include changes made since the initial query\n* transaction | transaction-response | batch | batch-response | collection : no particular assigned meaning\n\nThe timestamp value should be greater than the lastUpdated and other timestamps in the resources in the bundle, and it should be equal or earlier than the .meta.lastUpdated on the Bundle itself."
* total 0..1 SU unsignedInt "If search, the total number of matches" "If a set of search matches, this is the total number of entries of type 'match' across all pages in the search.  It does not include search.mode = 'include' or 'outcome' entries and it does not provide a count of the number of entries in the Bundle."
* total ^comment = "Only used if the bundle is a search result set. The total does not include resources such as OperationOutcome and included resources, only the total number of matching resources."
* total ^condition = "bdl-1"
* link 0..0 SU BackboneElement "Links related to this Bundle" "A series of links that provide context to this bundle."
* link ^comment = "Both Bundle.link and Bundle.entry.link are defined to support providing additional context when Bundles are used (e.g. [HATEOAS](http://en.wikipedia.org/wiki/HATEOAS)). \n\nBundle.entry.link corresponds to links found in the HTTP header if the resource in the entry was [read](http.html#read) directly.\n\nThis specification defines some specific uses of Bundle.link for [searching](search.html#conformance) and [paging](http.html#paging), but no specific uses for Bundle.entry.link, and no defined function in a transaction - the meaning is implementation specific."
* link.relation 1..1 SU string "See http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1" "A name which details the functional use for this link - see [http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1](http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1)."
* link.url 1..1 SU uri "Reference details for the link" "The reference details for the link."
* entry 0..0 SU BackboneElement "Entry in the bundle - will have a resource or information" "An entry in a bundle resource - will either contain a resource or information about a resource (transactions and history only)."
* entry obeys bdl-8 and bdl-5
* entry ^orderMeaning = "For bundles of type 'document' and 'message', the first resource is special (must be Composition or MessageHeader respectively). For all bundles, the meaning of the order of entries depends on the bundle type"
* entry.link 0..0 SU BackboneElement "Links related to this Bundle" "A series of links that provide context to this bundle."
* entry.link ^comment = "Both Bundle.link and Bundle.entry.link are defined to support providing additional context when Bundles are used (e.g. [HATEOAS](http://en.wikipedia.org/wiki/HATEOAS)). \n\nBundle.entry.link corresponds to links found in the HTTP header if the resource in the entry was [read](http.html#read) directly.\n\nThis specification defines some specific uses of Bundle.link for [searching](search.html#conformance) and [paging](http.html#paging), but no specific uses for Bundle.entry.link, and no defined function in a transaction - the meaning is implementation specific."
* entry.link.relation 1..1 SU string "See http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1" "A name which details the functional use for this link - see [http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1](http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1)."
* entry.link.url 1..1 SU uri "Reference details for the link" "The reference details for the link."
* entry.fullUrl 0..1 SU uri "URI for resource (Absolute URL server address or URI for UUID/OID)" "The Absolute URL for the resource.  The fullUrl SHALL NOT disagree with the id in the resource - i.e. if the fullUrl is not a urn:uuid, the URL shall be version-independent URL consistent with the Resource.id. The fullUrl is a version independent reference to the resource. The fullUrl element SHALL have a value except that: \n* fullUrl can be empty on a POST (although it does not need to when specifying a temporary id for reference in the bundle)\n* Results from operations might involve resources that are not identified."
* entry.fullUrl ^comment = "fullUrl might not be [unique in the context of a resource](bundle.html#bundle-unique). Note that since [FHIR resources do not need to be served through the FHIR API](references.html), the fullURL might be a URN or an absolute URL that does not end with the logical id of the resource (Resource.id). However, but if the fullUrl does look like a RESTful server URL (e.g. meets the [regex](references.html#regex), then the 'id' portion of the fullUrl SHALL end with the Resource.id.\n\nNote that the fullUrl is not the same as the canonical URL - it's an absolute url for an endpoint serving the resource (these will happen to have the same value on the canonical server for the resource with the canonical URL)."
* entry.resource 0..1 SU Resource "A resource in the bundle" "The Resource for the entry. The purpose/meaning of the resource is determined by the Bundle.type."
* entry.search 0..1 SU BackboneElement "Search related information" "Information about the search process that lead to the creation of this entry."
* entry.search ^condition = "bdl-2"
* entry.search.mode 0..1 SU code "match | include | outcome - why this is in the result set" "Why this entry is in the result set - whether it's included as a match or because of an _include requirement, or to convey information or warning information about the search process."
* entry.search.mode from http://hl7.org/fhir/ValueSet/search-entry-mode|4.0.1 (required)
* entry.search.mode ^comment = "There is only one mode. In some corner cases, a resource may be included because it is both a match and an include. In these circumstances, 'match' takes precedence."
* entry.search.mode ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* entry.search.mode ^binding.extension.valueString = "SearchEntryMode"
* entry.search.mode ^binding.description = "Why an entry is in the result set - whether it's included as a match or because of an _include requirement, or to convey information or warning information about the search process."
* entry.search.score 0..1 SU decimal "Search ranking (between 0 and 1)" "When searching, the server's search ranking score for the entry."
* entry.search.score ^comment = "Servers are not required to return a ranking score. 1 is most relevant, and 0 is least relevant. Often, search results are sorted by score, but the client may specify a different sort order.\n\nSee [Patient Match](patient-operation-match.html) for the EMPI search which relates to this element."
* entry.request 0..1 SU BackboneElement "Additional execution information (transaction/batch/history)" "Additional information about how this entry should be processed as part of a transaction or batch.  For history, it shows how the entry was processed to create the version contained in the entry."
* entry.request ^condition = "bdl-3"
* entry.request.method 1..1 SU code "GET | HEAD | POST | PUT | DELETE | PATCH" "In a transaction or batch, this is the HTTP action to be executed for this entry. In a history bundle, this indicates the HTTP action that occurred."
* entry.request.method from http://hl7.org/fhir/ValueSet/http-verb|4.0.1 (required)
* entry.request.method ^binding.extension.url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* entry.request.method ^binding.extension.valueString = "HTTPVerb"
* entry.request.method ^binding.description = "HTTP verbs (in the HTTP command line). See [HTTP rfc](https://tools.ietf.org/html/rfc7231) for details."
* entry.request.url 1..1 SU uri "URL for HTTP equivalent of this entry" "The URL for this entry, relative to the root (the address to which the request is posted)."
* entry.request.url ^comment = "E.g. for a Patient Create, the method would be \"POST\" and the URL would be \"Patient\". For a Patient Update, the method would be PUT and the URL would be \"Patient/[id]\"."
* entry.request.ifNoneMatch 0..1 SU string "For managing cache currency" "If the ETag values match, return a 304 Not Modified status. See the API documentation for [\"Conditional Read\"](http.html#cread)."
* entry.request.ifModifiedSince 0..1 SU instant "For managing cache currency" "Only perform the operation if the last updated date matches. See the API documentation for [\"Conditional Read\"](http.html#cread)."
* entry.request.ifMatch 0..1 SU string "For managing update contention" "Only perform the operation if the Etag value matches. For more information, see the API section [\"Managing Resource Contention\"](http.html#concurrency)."
* entry.request.ifNoneExist 0..1 SU string "For conditional creates" "Instruct the server not to perform the create if a specified resource already exists. For further information, see the API documentation for [\"Conditional Create\"](http.html#ccreate). This is just the query portion of the URL - what follows the \"?\" (not including the \"?\")."
* entry.response 0..1 SU BackboneElement "Results of execution (transaction/batch/history)" "Indicates the results of processing the corresponding 'request' entry in the batch or transaction being responded to or what the results of an operation where when returning history."
* entry.response ^condition = "bdl-4"
* entry.response.status 1..1 SU string "Status response code (text optional)" "The status code returned by processing this entry. The status SHALL start with a 3 digit HTTP code (e.g. 404) and may contain the standard HTTP description associated with the status code."
* entry.response.location 0..1 SU uri "The location (if the operation returns a location)" "The location header created by processing this operation, populated if the operation returns a location."
* entry.response.etag 0..1 SU string "The Etag for the resource (if relevant)" "The Etag for the resource, if the operation for the entry produced a versioned resource (see [Resource Metadata and Versioning](http.html#versioning) and [Managing Resource Contention](http.html#concurrency))."
* entry.response.etag ^comment = "Etags match the Resource.meta.versionId. The ETag has to match the version id in the header if a resource is included."
* entry.response.lastModified 0..1 SU instant "Server's date time modified" "The date/time that the resource was modified on the server."
* entry.response.lastModified ^comment = "This has to match the same time in the meta header (meta.lastUpdated) if a resource is included."
* entry.response.outcome 0..1 SU Resource "OperationOutcome with hints and warnings (for batch/transaction)" "An OperationOutcome containing hints and warnings produced as part of processing this entry in a batch or transaction."
* entry.response.outcome ^comment = "For a POST/PUT operation, this is the equivalent outcome that would be returned for prefer = operationoutcome - except that the resource is always returned whether or not the outcome is returned.\n\nThis outcome is not used for error responses in batch/transaction, only for hints and warnings. In a batch operation, the error will be in Bundle.entry.response, and for transaction, there will be a single OperationOutcome instead of a bundle in the case of an error."
* signature 0..1 SU Signature "Digital Signature" "Digital Signature - base64 encoded. XML-DSig or a JWT."
* signature ^comment = "The signature could be created by the \"author\" of the bundle or by the originating device.   Requirements around inclusion of a signature, verification of signatures and treatment of signed/non-signed bundles is implementation-environment specific."
* signature ^requirements = "A Signature holds an electronic representation of a signature and its supporting context in a FHIR accessible form. The signature may either be a cryptographic type (XML DigSig or a JWS), which is able to provide non-repudiation proof, or it may be a graphical image that represents a signature or a signature process. This element allows capturing signatures on documents, messages, transactions or even search responses, to support content-authentication, non-repudiation or other business cases. This is primarily relevant where the bundle may travel through multiple hops or via other mechanisms where HTTPS non-repudiation is insufficient."