Resource: Consent
Id: Consent
Description: "A record of a healthcare consumer’s  choices, which permits or denies identified recipient(s) or recipient role(s) to perform one or more actions within a given policy context, for specific purposes and periods of time."
* ^meta.lastUpdated = "2025-02-11T05:38:35.7073526+00:00"
* ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Foundation.Security"
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #cbcc
* ^url = "https://fhir.kemkes.go.id/r4/StructureDefinition/Consent"
* ^status = #draft
* ^date = "2019-11-01T09:29:23+11:00"
* ^publisher = "Health Level Seven International (Community Based Collaborative Care)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/homehealth/index.cfm"
* obeys ppc-4 and ppc-5 and ppc-2 and ppc-3 and ppc-1
* . ^short = "A healthcare consumer's  choices to permit or deny recipients or roles to perform actions for specific purposes and periods of time"
* . ^definition = "A record of a healthcare consumer’s  choices, which permits or denies identified recipient(s) or recipient role(s) to perform one or more actions within a given policy context, for specific purposes and periods of time."
* . ^comment = "Broadly, there are 3 key areas of consent for patients: Consent around sharing information (aka Privacy Consent Directive - Authorization to Collect, Use, or Disclose information), consent for specific treatment, or kinds of treatment, and general advance care directives."
* identifier 0..0 SU Identifier "Identifier for this record (external references)" "Unique identifier for this copy of the Consent Statement."
* identifier ^comment = "This identifier identifies this copy of the consent. Where this identifier is also used elsewhere as the identifier for a consent record (e.g. a CDA consent document) then the consent details are expected to be the same."
* identifier ^example.label = "General"
* identifier ^example.valueIdentifier.system = "urn:ietf:rfc:3986"
* identifier ^example.valueIdentifier.value = "Local eCMS identifier"
* status 1..1 ?! SU code "draft | proposed | active | rejected | inactive | entered-in-error" "Indicates the current state of this consent."
* status from http://hl7.org/fhir/ValueSet/consent-state-codes|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains the codes rejected and entered-in-error that mark the Consent as not currently valid."
* status ^requirements = "The Consent Directive that is pointed to might be in various lifecycle states, e.g., a revoked Consent Directive."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension[=].valueString = "ConsentState"
* status ^binding.description = "Indicates the state of the consent."
* scope 1..1 ?! SU CodeableConcept "Which of the four areas this resource covers (extensible)" "A selector of the type of consent being presented: ADR, Privacy, Treatment, Research.  This list is now extensible."
* scope from http://hl7.org/fhir/ValueSet/consent-scope (extensible)
* scope ^isModifierReason = "Allows changes to codes based on scope selection"
* scope ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* scope ^binding.extension[=].valueString = "ConsentScope"
* scope ^binding.description = "The four anticipated uses for the Consent Resource."
* category 1..0 SU CodeableConcept "Classification of the consent statement - for indexing/retrieval" "A classification of the type of consents found in the statement. This element supports indexing and retrieval of consent statements."
* category from http://hl7.org/fhir/ValueSet/consent-category (extensible)
* category ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* category ^binding.extension[=].valueString = "ConsentCategory"
* category ^binding.description = "A classification of the type of consents found in a consent statement."
* patient 0..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Patient) "Who the consent applies to" "The patient/healthcare consumer to whom this consent applies."
* patient ^comment = "Commonly, the patient the consent pertains to is the author, but for young and old people, it may be some other person."
* dateTime 0..1 SU dateTime "When this Consent was created or indexed" "When this  Consent was issued / created / indexed."
* dateTime ^comment = "This is not the time of the original consent, but the time that this statement was made or derived."
* performer 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/Organization or http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/RelatedPerson or http://hl7.org/fhir/StructureDefinition/PractitionerRole) "Who is agreeing to the policy and rules" "Either the Grantor, which is the entity responsible for granting the rights listed in a Consent Directive or the Grantee, which is the entity responsible for complying with the Consent Directive, including any obligations or limitations on authorizations and enforcement of prohibitions."
* performer ^comment = "Commonly, the patient the consent pertains to is the consentor, but particularly for young and old people, it may be some other person - e.g. a legal guardian."
* performer ^alias = "consentor"
* organization 0..0 SU Reference(http://hl7.org/fhir/StructureDefinition/Organization) "Custodian of the consent" "The organization that manages the consent, and the framework within which it is executed."
* organization ^alias = "custodian"
* source[x] 0..1 SU Attachment or Reference(http://hl7.org/fhir/StructureDefinition/Consent or http://hl7.org/fhir/StructureDefinition/DocumentReference or http://hl7.org/fhir/StructureDefinition/Contract or http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse) "Source from which this consent is taken" "The source on which this consent statement is based. The source might be a scanned original paper form, or a reference to a consent that links back to such a source, a reference to a document repository (e.g. XDS) that stores the original consent document."
* source[x] ^comment = "The source can be contained inline (Attachment), referenced directly (Consent), referenced in a consent repository (DocumentReference), or simply by an identifier (Identifier), e.g. a CDA document id."
* policy 0..0 BackboneElement "Policies covered by this consent" "The references to the policies that are included in this consent scope. Policies may be organizational, but are often defined jurisdictionally, or in law."
* policy.authority 0..1 uri "Enforcement source for policy" "Entity or Organization having regulatory jurisdiction or accountability for  enforcing policies pertaining to Consent Directives."
* policy.authority ^condition = "ppc-1"
* policy.uri 0..1 uri "Specific policy covered by this consent" "The references to the policies that are included in this consent scope. Policies may be organizational, but are often defined jurisdictionally, or in law."
* policy.uri ^comment = "This element is for discoverability / documentation and does not modify or qualify the policy rules."
* policy.uri ^condition = "ppc-1"
* policyRule 0..1 SU CodeableConcept "Regulation that this consents to" "A reference to the specific base computable regulation or policy."
* policyRule from http://hl7.org/fhir/ValueSet/consent-policy (extensible)
* policyRule ^comment = "If the policyRule is absent, computable consent would need to be constructed from the elements of the Consent resource."
* policyRule ^requirements = "Might be a unique identifier of a policy set in XACML, or other rules engine."
* policyRule ^condition = "ppc-1"
* policyRule ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* policyRule ^binding.extension[=].valueString = "ConsentPolicyRule"
* policyRule ^binding.description = "Regulatory policy examples."
* verification 0..0 SU BackboneElement "Consent Verified by patient or family" "Whether a treatment instruction (e.g. artificial respiration yes or no) was verified with the patient, his/her family or another authorized person."
* verification.verified 1..1 SU boolean "Has been verified" "Has the instruction been verified."
* verification.verifiedWith 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/RelatedPerson) "Person who verified" "Who verified the instruction (Patient, Relative or other Authorized Person)."
* verification.verificationDate 0..1 dateTime "When consent verified" "Date verification was collected."
* provision 0..1 SU BackboneElement "Constraints to the base Consent.policyRule" "An exception to the base policy of this consent. An exception can be an addition or removal of access permissions."
* provision ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-explicit-type-name"
* provision ^extension[=].valueString = "provision"
* provision.type 0..1 SU code "deny | permit" "Action  to take - permit or deny - when the rule conditions are met.  Not permitted in root rule, required in all nested rules."
* provision.type from http://hl7.org/fhir/ValueSet/consent-provision-type|4.0.1 (required)
* provision.type ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.type ^binding.extension[=].valueString = "ConsentProvisionType"
* provision.type ^binding.description = "How a rule statement is applied, such as adding additional consent or removing consent."
* provision.period 0..1 SU Period "Timeframe for this rule" "The timeframe in this rule is valid."
* provision.actor 0..0 BackboneElement "Who|what controlled by this rule (or group, by role)" "Who or what is controlled by this rule. Use group to identify a set of actors by some property they share (e.g. 'admitting officers')."
* provision.actor ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-explicit-type-name"
* provision.actor ^extension[=].valueString = "provisionActor"
* provision.actor ^meaningWhenMissing = "There is no specific actor associated with the exception"
* provision.actor.role 1..1 CodeableConcept "How the actor is involved" "How the individual is involved in the resources content that is described in the exception."
* provision.actor.role from http://hl7.org/fhir/ValueSet/security-role-type (extensible)
* provision.actor.role ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.actor.role ^binding.extension[=].valueString = "ConsentActorRole"
* provision.actor.role ^binding.description = "How an actor is involved in the consent considerations."
* provision.actor.reference 1..1 Reference(http://hl7.org/fhir/StructureDefinition/Device or http://hl7.org/fhir/StructureDefinition/Group or http://hl7.org/fhir/StructureDefinition/CareTeam or http://hl7.org/fhir/StructureDefinition/Organization or http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/RelatedPerson or http://hl7.org/fhir/StructureDefinition/PractitionerRole) "Resource for the actor (or group, by role)" "The resource that identifies the actor. To identify actors by type, use group to identify a set of actors by some property they share (e.g. 'admitting officers')."
* provision.action 0..0 SU CodeableConcept "Actions controlled by this rule" "Actions controlled by this Rule."
* provision.action from http://hl7.org/fhir/ValueSet/consent-action (example)
* provision.action ^comment = "Note that this is the direct action (not the grounds for the action covered in the purpose element). At present, the only action in the understood and tested scope of this resource is 'read'."
* provision.action ^meaningWhenMissing = "all actions"
* provision.action ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.action ^binding.extension[=].valueString = "ConsentAction"
* provision.action ^binding.description = "Detailed codes for the consent action."
* provision.securityLabel 0..0 SU Coding "Security Labels that define affected resources" "A security label, comprised of 0..* security label fields (Privacy tags), which define which resources are controlled by this exception."
* provision.securityLabel from http://hl7.org/fhir/ValueSet/security-labels (extensible)
* provision.securityLabel ^comment = "If the consent specifies a security label of \"R\" then it applies to all resources that are labeled \"R\" or lower. E.g. for Confidentiality, it's a high water mark. For other kinds of security labels, subsumption logic applies. When the purpose of use tag is on the data, access request purpose of use shall not conflict."
* provision.securityLabel ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.securityLabel ^binding.extension[=].valueString = "SecurityLabels"
* provision.securityLabel ^binding.extension[+].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-isCommonBinding"
* provision.securityLabel ^binding.extension[=].valueBoolean = true
* provision.securityLabel ^binding.description = "Security Labels from the Healthcare Privacy and Security Classification System."
* provision.purpose 0..0 SU Coding "Context of activities covered by this rule" "The context of the activities a user is taking - why the user is accessing the data - that are controlled by this rule."
* provision.purpose from http://terminology.hl7.org/ValueSet/v3-PurposeOfUse (extensible)
* provision.purpose ^comment = "When the purpose of use tag is on the data, access request purpose of use shall not conflict."
* provision.purpose ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.purpose ^binding.extension[=].valueString = "PurposeOfUse"
* provision.purpose ^binding.description = "What purposes of use are controlled by this exception. If more than one label is specified, operations must have all the specified labels."
* provision.class 0..0 SU Coding "e.g. Resource Type, Profile, CDA, etc." "The class of information covered by this rule. The type can be a FHIR resource type, a profile on a type, or a CDA document, or some other type that indicates what sort of information the consent relates to."
* provision.class from http://hl7.org/fhir/ValueSet/consent-content-class (extensible)
* provision.class ^comment = "Multiple types are or'ed together. The intention of the contentType element is that the codes refer to profiles or document types defined in a standard or an implementation guide somewhere."
* provision.class ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.class ^binding.extension[=].valueString = "ConsentContentClass"
* provision.class ^binding.description = "The class (type) of information a consent rule covers."
* provision.code 0..0 SU CodeableConcept "e.g. LOINC or SNOMED CT code, etc. in the content" "If this code is found in an instance, then the rule applies."
* provision.code from http://hl7.org/fhir/ValueSet/consent-content-code (example)
* provision.code ^comment = "Typical use of this is a Document code with class = CDA."
* provision.code ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.code ^binding.extension[=].valueString = "ConsentContentCode"
* provision.code ^binding.description = "If this code is found in an instance, then the exception applies."
* provision.dataPeriod 0..1 SU Period "Timeframe for data controlled by this rule" "Clinical or Operational Relevant period of time that bounds the data controlled by this rule."
* provision.dataPeriod ^comment = "This has a different sense to the Consent.period - that is when the consent agreement holds. This is the time period of the data that is controlled by the agreement."
* provision.data 0..0 SU BackboneElement "Data controlled by this rule" "The resources controlled by this rule if specific resources are referenced."
* provision.data ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-explicit-type-name"
* provision.data ^extension[=].valueString = "provisionData"
* provision.data ^meaningWhenMissing = "all data"
* provision.data.meaning 1..1 SU code "instance | related | dependents | authoredby" "How the resource reference is interpreted when testing consent restrictions."
* provision.data.meaning from http://hl7.org/fhir/ValueSet/consent-data-meaning|4.0.1 (required)
* provision.data.meaning ^binding.extension[0].url = "http://hl7.org/fhir/StructureDefinition/elementdefinition-bindingName"
* provision.data.meaning ^binding.extension[=].valueString = "ConsentDataMeaning"
* provision.data.meaning ^binding.description = "How a resource reference is interpreted when testing consent restrictions."
* provision.data.reference 1..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Resource) "The actual data reference" "A reference to a specific resource that defines which resources are covered by this consent."
* provision.provision 0..* contentReference http://hl7.org/fhir/StructureDefinition/DomainResource#Consent.provision "Nested Exception Rules" "Rules which provide exceptions to the base rule or subrules."