Resource: Account
Id: Account
Description: "A financial tool for tracking value accrued for a particular purpose.  In the healthcare field, used to track charges for a patient, cost centers, etc."
* ^meta.lastUpdated = "2019-10-31T22:29:23.356+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Financial.General"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #pa
* ^status = #draft
* ^date = "2023-05-12T03:54:04.8907436+00:00"
* ^publisher = "Health Level Seven International (Patient Administration)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/pafm/index.cfm"
* . ^short = "Tracks balance, charges, for patient or cost center"
* . ^definition = "A financial tool for tracking value accrued for a particular purpose.  In the healthcare field, used to track charges for a patient, cost centers, etc."
* . ^alias[0] = "Cost center"
* . ^alias[+] = "Record"
* identifier 0..* SU Identifier "Account number" "Unique identifier used to reference the account.  Might or might not be intended for human use (e.g. credit card number)."
* status 1..1 ?! SU code "active | inactive | entered-in-error | on-hold | unknown" "Indicates whether the account is presently used/usable or not."
* status from http://hl7.org/fhir/ValueSet/account-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains the codes inactive and entered-in-error that mark the Account as not currently valid."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "AccountStatus"
* status ^binding.description = "Indicates whether the account is available to be used."
* type 0..1 SU CodeableConcept "E.g. patient, expense, depreciation" "Categorizes the account for reporting and searching purposes."
* type from http://hl7.org/fhir/ValueSet/account-type (example)
* type ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* type ^binding.extension.valueString = "AccountType"
* type ^binding.description = "The usage type of this account, permits categorization of accounts."
* name 0..1 SU string "Human-readable label" "Name used for the account when displaying it to humans in reports, etc."
* name ^alias[0] = "Title"
* subject 0..* SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Device or https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Location or https://fhir.kemkes.go.id/r4/StructureDefinition/HealthcareService or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "The entity that caused the expenses" "Identifies the entity which incurs the expenses. While the immediate recipients of services or goods might be entities related to the subject, the expenses were ultimately incurred by the subject of the Account."
* subject ^comment = "Accounts can be applied to non-patients for tracking other non-patient related activities, such as group services (patients not tracked, and costs charged to another body), or might not be allocated."
* subject ^alias[0] = "target"
* servicePeriod 0..1 SU Period "Transaction window" "The date range of services associated with this account."
* servicePeriod ^comment = "It is possible for transactions to be posted outside the service period, as long as the service was provided within the defined service period."
* coverage 0..* SU BackboneElement "The party(s) that are responsible for covering the payment of this account, and what order should they be applied to the account" "The party(s) that are responsible for covering the payment of this account, and what order should they be applied to the account."
* coverage ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* coverage ^extension[=].valueString = "Coverage"
* coverage ^comment = "Typically. this may be some form of insurance, internal charges, or self-pay.\n\nLocal or jurisdictional business rules may determine which coverage covers which types of billable items charged to the account, and in which order.\nWhere the order is important, a local/jurisdictional extension may be defined to specify the order for the type of charge."
* coverage.coverage 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Coverage) "The party(s), such as insurances, that may contribute to the payment of this account" "The party(s) that contribute to payment (or part of) of the charges applied to this account (including self-pay).\n\nA coverage may only be responsible for specific types of charges, and the sequence of the coverages in the account could be important when processing billing."
* coverage.priority 0..1 SU positiveInt "The priority of the coverage in the context of this account" "The priority of the coverage in the context of this account."
* coverage.priority ^comment = "It is common in some jurisdictions for there to be multiple coverages allocated to an account, and a sequence is required to order the settling of the account (often with insurance claiming)."
* coverage.priority ^alias[0] = "coordination of benefit priority"
* owner 0..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Entity managing the Account" "Indicates the service area, hospital, department, etc. with responsibility for managing the Account."
* description 0..1 SU string "Explanation of purpose/use" "Provides additional information about what the account tracks and how it is used."
* guarantor 0..* BackboneElement "The parties ultimately responsible for balancing the Account" "The parties responsible for balancing the account if other payment options fall short."
* guarantor ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* guarantor ^extension[=].valueString = "Guarantor"
* guarantor.party 1..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Responsible entity" "The entity who is responsible."
* guarantor.onHold 0..1 boolean "Credit or other hold applied" "A guarantor may be placed on credit hold or otherwise have their role temporarily suspended."
* guarantor.period 0..1 Period "Guarantee account during" "The timeframe during which the guarantor accepts responsibility for the account."
* partOf 0..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Account) "Reference to a parent Account" "Reference to a parent Account."