Resource: CarePlan
Id: CarePlan
Description: "Describes the intention of how one or more practitioners intend to deliver care for a particular patient, group or community for a period of time, possibly limited to care for a specific condition or set of conditions."
* ^meta.lastUpdated = "2019-10-31T22:29:23.356+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Clinical.Care Provision"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #pc
* ^status = #draft
* ^date = "2023-05-12T03:46:03.1771008+00:00"
* ^publisher = "Health Level Seven International (Patient Care)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/patientcare/index.cfm"
* . ^short = "Healthcare plan for patient or group"
* . ^definition = "Describes the intention of how one or more practitioners intend to deliver care for a particular patient, group or community for a period of time, possibly limited to care for a specific condition or set of conditions."
* . ^alias = "Care Team"
* identifier undefined..undefined SU Identifier "External Ids for this plan" "Business identifiers assigned to this care plan by the performer or other systems which remain constant as the resource is updated and propagates from server to server."
* identifier ^comment = "This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number."
* identifier ^requirements = "Allows identification of the care plan as it is known by various participating systems and in a way that remains consistent across servers."
* instantiatesCanonical undefined..undefined SU Canonical(https://fhir.kemkes.go.id/r4/StructureDefinition/PlanDefinition or https://fhir.kemkes.go.id/r4/StructureDefinition/Questionnaire or https://fhir.kemkes.go.id/r4/StructureDefinition/Measure or https://fhir.kemkes.go.id/r4/StructureDefinition/ActivityDefinition or https://fhir.kemkes.go.id/r4/StructureDefinition/OperationDefinition) "Instantiates FHIR protocol or definition" "The URL pointing to a FHIR-defined protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan."
* instantiatesUri undefined..undefined SU uri "Instantiates external protocol or definition" "The URL pointing to an externally maintained protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan."
* instantiatesUri ^comment = "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier."
* basedOn undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/CarePlan) "Fulfills CarePlan" "A care plan that is fulfilled in whole or in part by this care plan."
* basedOn ^requirements = "Allows tracing of the care plan and tracking whether proposals/recommendations were acted upon."
* basedOn ^alias = "fulfills"
* basedOn ^type.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-hierarchy"
* basedOn ^type.extension.valueBoolean = true
* replaces undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/CarePlan) "CarePlan replaced by this CarePlan" "Completed or terminated care plan whose function is taken by this new care plan."
* replaces ^comment = "The replacement could be because the initial care plan was immediately rejected (due to an issue) or because the previous care plan was completed, but the need for the action described by the care plan remains ongoing."
* replaces ^requirements = "Allows tracing the continuation of a therapy or administrative process instantiated through multiple care plans."
* replaces ^alias = "supersedes"
* replaces ^type.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-hierarchy"
* replaces ^type.extension.valueBoolean = true
* partOf undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/CarePlan) "Part of referenced CarePlan" "A larger care plan of which this particular care plan is a component or step."
* partOf ^comment = "Each care plan is an independent request, such that having a care plan be part of another care plan can cause issues with cascading statuses.  As such, this element is still being discussed."
* partOf ^type.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-hierarchy"
* partOf ^type.extension.valueBoolean = true
* status 1..1 ?! SU code "draft | active | on-hold | revoked | completed | entered-in-error | unknown" "Indicates whether the plan is currently being acted upon, represents future intentions or is now a historical record."
* status from http://hl7.org/fhir/ValueSet/request-status|4.0.1 (required)
* status ^comment = "The unknown code is not to be used to convey other statuses.  The unknown code should be used when one of the statuses applies, but the authoring system doesn't know the current state of the care plan.\n\nThis element is labeled as a modifier because the status contains the code entered-in-error that marks the plan as not currently valid."
* status ^requirements = "Allows clinicians to determine whether the plan is actionable or not."
* status ^isModifierReason = "This element is labeled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "CarePlanStatus"
* status ^binding.description = "Indicates whether the plan is currently being acted upon, represents future intentions or is now a historical record."
* intent 1..1 ?! SU code "proposal | plan | order | option" "Indicates the level of authority/intentionality associated with the care plan and where the care plan fits into the workflow chain."
* intent from http://hl7.org/fhir/ValueSet/care-plan-intent|4.0.1 (required)
* intent ^comment = "This element is labeled as a modifier because the intent alters when and how the resource is actually applicable."
* intent ^requirements = "Proposals/recommendations, plans and orders all use the same structure and can exist in the same fulfillment chain."
* intent ^isModifierReason = "This element changes the interpretation of all descriptive attributes. For example \"the time the request is recommended to occur\" vs. \"the time the request is authorized to occur\" or \"who is recommended to perform the request\" vs. \"who is authorized to perform the request\""
* intent ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* intent ^binding.extension.valueString = "CarePlanIntent"
* intent ^binding.description = "Codes indicating the degree of authority/intentionality associated with a care plan."
* category undefined..undefined SU CodeableConcept "Type of plan" "Identifies what \"kind\" of plan this is to support differentiation between multiple co-existing plans; e.g. \"Home health\", \"psychiatric\", \"asthma\", \"disease management\", \"wellness plan\", etc."
* category from http://hl7.org/fhir/ValueSet/care-plan-category (example)
* category ^comment = "There may be multiple axes of categorization and one plan may serve multiple purposes.  In some cases, this may be redundant with references to CarePlan.concern."
* category ^requirements = "Used for filtering what plan(s) are retrieved and displayed to different types of users."
* category ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* category ^binding.extension.valueString = "CarePlanCategory"
* category ^binding.description = "Identifies what \"kind\" of plan this is to support differentiation between multiple co-existing plans; e.g. \"Home health\", \"psychiatric\", \"asthma\", \"disease management\", etc."
* title undefined..1 SU string "Human-friendly name for the care plan" "Human-friendly name for the care plan."
* description undefined..1 SU string "Summary of nature of plan" "A description of the scope and nature of the plan."
* description ^requirements = "Provides more detail than conveyed by category."
* subject 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Group) "Who the care plan is for" "Identifies the patient or group whose intended care is described by the plan."
* subject ^alias = "patient"
* encounter undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Encounter) "Encounter created as part of" "The Encounter during which this CarePlan was created or to which the creation of this record is tightly associated."
* encounter ^comment = "This will typically be the encounter the event occurred within, but some activities may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter. CarePlan activities conducted as a result of the care plan may well occur as part of other encounters."
* period undefined..1 SU Period "Time period plan covers" "Indicates when the plan did (or is intended to) come into effect and end."
* period ^comment = "Any activities scheduled as part of the plan should be constrained to the specified period regardless of whether the activities are planned within a single encounter/episode or across multiple encounters/episodes (e.g. the longitudinal management of a chronic condition)."
* period ^requirements = "Allows tracking what plan(s) are in effect at a particular time."
* period ^alias = "timing"
* created undefined..1 SU dateTime "Date record was first recorded" "Represents when this particular CarePlan record was created in the system, which is often a system-generated date."
* created ^alias = "authoredOn"
* author undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Device or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization or https://fhir.kemkes.go.id/r4/StructureDefinition/CareTeam) "Who is the designated responsible party" "When populated, the author is responsible for the care plan.  The care plan is attributed to the author."
* author ^comment = "The author may also be a contributor.  For example, an organization can be an author, but not listed as a contributor."
* contributor undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Device or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization or https://fhir.kemkes.go.id/r4/StructureDefinition/CareTeam) "Who provided the content of the care plan" "Identifies the individual(s) or organization who provided the contents of the care plan."
* contributor ^comment = "Collaborative care plans may have multiple contributors."
* careTeam undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/CareTeam) "Who's involved in plan?" "Identifies all people and organizations who are expected to be involved in the care envisioned by this plan."
* careTeam ^requirements = "Allows representation of care teams, helps scope care plan.  In some cases may be a determiner of access permissions."
* addresses undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Condition) "Health issues this plan addresses" "Identifies the conditions/problems/concerns/diagnoses/etc. whose management and/or mitigation are handled by this plan."
* addresses ^comment = "When the diagnosis is related to an allergy or intolerance, the Condition and AllergyIntolerance resources can both be used. However, to be actionable for decision support, using Condition alone is not sufficient as the allergy or intolerance condition needs to be represented as an AllergyIntolerance."
* addresses ^requirements = "Links plan to the conditions it manages.  The element can identify risks addressed by the plan as well as active conditions.  (The Condition resource can include things like \"at risk for hypertension\" or \"fall risk\".)  Also scopes plans - multiple plans may exist addressing different concerns."
* supportingInfo undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "Information considered as part of plan" "Identifies portions of the patient's record that specifically influenced the formation of the plan.  These might include comorbidities, recent procedures, limitations, recent assessments, etc."
* supportingInfo ^comment = "Use \"concern\" to identify specific conditions addressed by the care plan."
* supportingInfo ^requirements = "Identifies barriers and other considerations associated with the care plan."
* goal undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Goal) "Desired outcome of plan" "Describes the intended objective(s) of carrying out the care plan."
* goal ^comment = "Goal can be achieving a particular change or merely maintaining a current state or even slowing a decline."
* goal ^requirements = "Provides context for plan.  Allows plan effectiveness to be evaluated by clinicians."
* activity undefined..undefined BackboneElement "Action to occur as part of plan" "Identifies a planned action to occur as part of the plan.  For example, a medication to be used, lab tests to perform, self-monitoring, education, etc."
* activity obeys cpl-3
* activity ^requirements = "Allows systems to prompt for performance of planned activities, and validate plans against best practice."
* activity.outcomeCodeableConcept undefined..undefined CodeableConcept "Results of the activity" "Identifies the outcome at the point when the status of the activity is assessed.  For example, the outcome of an education activity could be patient understands (or not)."
* activity.outcomeCodeableConcept from http://hl7.org/fhir/ValueSet/care-plan-activity-outcome (example)
* activity.outcomeCodeableConcept ^comment = "Note that this should not duplicate the activity status (e.g. completed or in progress)."
* activity.outcomeCodeableConcept ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* activity.outcomeCodeableConcept ^binding.extension.valueString = "CarePlanActivityOutcome"
* activity.outcomeCodeableConcept ^binding.description = "Identifies the results of the activity."
* activity.outcomeReference undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "Appointment, Encounter, Procedure, etc." "Details of the outcome or action resulting from the activity.  The reference to an \"event\" resource, such as Procedure or Encounter or Observation, is the result/outcome of the activity itself.  The activity can be conveyed using CarePlan.activity.detail OR using the CarePlan.activity.reference (a reference to a “request” resource)."
* activity.outcomeReference ^comment = "The activity outcome is independent of the outcome of the related goal(s).  For example, if the goal is to achieve a target body weight of 150 lbs and an activity is defined to diet, then the activity outcome could be calories consumed whereas the goal outcome is an observation for the actual body weight measured."
* activity.outcomeReference ^requirements = "Links plan to resulting actions."
* activity.progress undefined..undefined Annotation "Comments about the activity status/progress" "Notes about the adherence/status/progress of the activity."
* activity.progress ^comment = "This element should NOT be used to describe the activity to be performed - that occurs either within the resource pointed to by activity.detail.reference or in activity.detail.description."
* activity.progress ^requirements = "Can be used to capture information about adherence, progress, concerns, etc."
* activity.reference undefined..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Appointment or https://fhir.kemkes.go.id/r4/StructureDefinition/CommunicationRequest or https://fhir.kemkes.go.id/r4/StructureDefinition/DeviceRequest or https://fhir.kemkes.go.id/r4/StructureDefinition/MedicationRequest or https://fhir.kemkes.go.id/r4/StructureDefinition/NutritionOrder or https://fhir.kemkes.go.id/r4/StructureDefinition/Task or https://fhir.kemkes.go.id/r4/StructureDefinition/ServiceRequest or https://fhir.kemkes.go.id/r4/StructureDefinition/VisionPrescription or https://fhir.kemkes.go.id/r4/StructureDefinition/RequestGroup) "Activity details defined in specific resource" "The details of the proposed activity represented in a specific resource."
* activity.reference ^comment = "Standard extension exists ([resource-pertainsToGoal](extension-resource-pertainstogoal.html)) that allows goals to be referenced from any of the referenced resources in CarePlan.activity.reference.  \rThe goal should be visible when the resource referenced by CarePlan.activity.reference is viewed independently from the CarePlan.  Requests that are pointed to by a CarePlan using this element should *not* point to this CarePlan using the \"basedOn\" element.  i.e. Requests that are part of a CarePlan are not \"based on\" the CarePlan."
* activity.reference ^requirements = "Details in a form consistent with other applications and contexts of use."
* activity.reference ^condition = "cpl-3"
* activity.detail undefined..1 BackboneElement "In-line definition of activity" "A simple summary of a planned activity suitable for a general care plan system (e.g. form driven) that doesn't know about specific resources such as procedure etc."
* activity.detail ^requirements = "Details in a simple form for generic care plan systems."
* activity.detail ^condition = "cpl-3"
* activity.detail.kind undefined..1 code "Appointment | CommunicationRequest | DeviceRequest | MedicationRequest | NutritionOrder | Task | ServiceRequest | VisionPrescription" "A description of the kind of resource the in-line definition of a care plan activity is representing.  The CarePlan.activity.detail is an in-line definition when a resource is not referenced using CarePlan.activity.reference.  For example, a MedicationRequest, a ServiceRequest, or a CommunicationRequest."
* activity.detail.kind from http://hl7.org/fhir/ValueSet/care-plan-activity-kind|4.0.1 (required)
* activity.detail.kind ^requirements = "May determine what types of extensions are permitted."
* activity.detail.kind ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* activity.detail.kind ^binding.extension.valueString = "CarePlanActivityKind"
* activity.detail.kind ^binding.description = "Resource types defined as part of FHIR that can be represented as in-line definitions of a care plan activity."
* activity.detail.instantiatesCanonical undefined..undefined Canonical(https://fhir.kemkes.go.id/r4/StructureDefinition/PlanDefinition or https://fhir.kemkes.go.id/r4/StructureDefinition/ActivityDefinition or https://fhir.kemkes.go.id/r4/StructureDefinition/Questionnaire or https://fhir.kemkes.go.id/r4/StructureDefinition/Measure or https://fhir.kemkes.go.id/r4/StructureDefinition/OperationDefinition) "Instantiates FHIR protocol or definition" "The URL pointing to a FHIR-defined protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan activity."
* activity.detail.instantiatesCanonical ^requirements = "Allows Questionnaires that the patient (or practitioner) should fill in to fulfill the care plan activity."
* activity.detail.instantiatesUri undefined..undefined uri "Instantiates external protocol or definition" "The URL pointing to an externally maintained protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan activity."
* activity.detail.instantiatesUri ^comment = "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier."
* activity.detail.instantiatesUri ^requirements = "Allows Questionnaires that the patient (or practitioner) should fill in to fulfill the care plan activity."
* activity.detail.code undefined..1 CodeableConcept "Detail type of activity" "Detailed description of the type of planned activity; e.g. what lab test, what procedure, what kind of encounter."
* activity.detail.code from http://hl7.org/fhir/ValueSet/procedure-code (example)
* activity.detail.code ^comment = "Tends to be less relevant for activities involving particular products.  Codes should not convey negation - use \"prohibited\" instead."
* activity.detail.code ^requirements = "Allows matching performed to planned as well as validation against protocols."
* activity.detail.code ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* activity.detail.code ^binding.extension.valueString = "CarePlanActivityType"
* activity.detail.code ^binding.description = "Detailed description of the type of activity; e.g. What lab test, what procedure, what kind of encounter."
* activity.detail.reasonCode undefined..undefined CodeableConcept "Why activity should be done or why activity was prohibited" "Provides the rationale that drove the inclusion of this particular activity as part of the plan or the reason why the activity was prohibited."
* activity.detail.reasonCode from http://hl7.org/fhir/ValueSet/clinical-findings (example)
* activity.detail.reasonCode ^comment = "This could be a diagnosis code.  If a full condition record exists or additional detail is needed, use reasonCondition instead."
* activity.detail.reasonCode ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* activity.detail.reasonCode ^binding.extension.valueString = "CarePlanActivityReason"
* activity.detail.reasonCode ^binding.description = "Identifies why a care plan activity is needed.  Can include any health condition codes as well as such concepts as \"general wellness\", prophylaxis, surgical preparation, etc."
* activity.detail.reasonReference undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Condition or https://fhir.kemkes.go.id/r4/StructureDefinition/Observation or https://fhir.kemkes.go.id/r4/StructureDefinition/DiagnosticReport or https://fhir.kemkes.go.id/r4/StructureDefinition/DocumentReference) "Why activity is needed" "Indicates another resource, such as the health condition(s), whose existence justifies this request and drove the inclusion of this particular activity as part of the plan."
* activity.detail.reasonReference ^comment = "Conditions can be identified at the activity level that are not identified as reasons for the overall plan."
* activity.detail.goal undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Goal) "Goals this activity relates to" "Internal reference that identifies the goals that this activity is intended to contribute towards meeting."
* activity.detail.goal ^requirements = "So that participants know the link explicitly."
* activity.detail.status 1..1 ?! code "not-started | scheduled | in-progress | on-hold | completed | cancelled | stopped | unknown | entered-in-error" "Identifies what progress is being made for the specific activity."
* activity.detail.status from http://hl7.org/fhir/ValueSet/care-plan-activity-status|4.0.1 (required)
* activity.detail.status ^comment = "Some aspects of status can be inferred based on the resources linked in actionTaken.  Note that \"status\" is only as current as the plan was most recently updated.  \nThe unknown code is not to be used to convey other statuses.  The unknown code should be used when one of the statuses applies, but the authoring system doesn't know the current state of the activity."
* activity.detail.status ^requirements = "Indicates progress against the plan, whether the activity is still relevant for the plan."
* activity.detail.status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the activity should not be treated as valid"
* activity.detail.status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* activity.detail.status ^binding.extension.valueString = "CarePlanActivityStatus"
* activity.detail.status ^binding.description = "Codes that reflect the current state of a care plan activity within its overall life cycle."
* activity.detail.statusReason undefined..1 CodeableConcept "Reason for current status" "Provides reason why the activity isn't yet started, is on hold, was cancelled, etc."
* activity.detail.statusReason ^comment = "Will generally not be present if status is \"complete\".  Be sure to prompt to update this (or at least remove the existing value) if the status is changed."
* activity.detail.doNotPerform undefined..1 ?! boolean "If true, activity is prohibiting action" "If true, indicates that the described activity is one that must NOT be engaged in when following the plan.  If false, or missing, indicates that the described activity is one that should be engaged in when following the plan."
* activity.detail.doNotPerform ^comment = "This element is labeled as a modifier because it marks an activity as an activity that is not to be performed."
* activity.detail.doNotPerform ^requirements = "Captures intention to not do something that may have been previously typical."
* activity.detail.doNotPerform ^meaningWhenMissing = "If missing indicates that the described activity is one that should be engaged in when following the plan."
* activity.detail.doNotPerform ^isModifierReason = "If true this element negates the specified action. For example, instead of a request for a procedure, it is a request for the procedure to not occur."
* activity.detail.scheduled[x] undefined..1 Timing or Period or string "When activity is to occur" "The period, timing or frequency upon which the described activity is to occur."
* activity.detail.scheduled[x] ^requirements = "Allows prompting for activities and detection of missed planned activities."
* activity.detail.location undefined..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Location) "Where it should happen" "Identifies the facility where the activity will occur; e.g. home, hospital, specific clinic, etc."
* activity.detail.location ^comment = "May reference a specific clinical location or may identify a type of location."
* activity.detail.location ^requirements = "Helps in planning of activity."
* activity.detail.performer undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson or https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/CareTeam or https://fhir.kemkes.go.id/r4/StructureDefinition/HealthcareService or https://fhir.kemkes.go.id/r4/StructureDefinition/Device) "Who will be responsible?" "Identifies who's expected to be involved in the activity."
* activity.detail.performer ^comment = "A performer MAY also be a participant in the care plan."
* activity.detail.performer ^requirements = "Helps in planning of activity."
* activity.detail.product[x] undefined..1 CodeableConcept or Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Medication or https://fhir.kemkes.go.id/r4/StructureDefinition/Substance) "What is to be administered/supplied" "Identifies the food, drug or other product to be consumed or supplied in the activity."
* activity.detail.product[x] from http://hl7.org/fhir/ValueSet/medication-codes (example)
* activity.detail.product[x] ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* activity.detail.product[x] ^binding.extension.valueString = "CarePlanProduct"
* activity.detail.product[x] ^binding.description = "A product supplied or administered as part of a care plan activity."
* activity.detail.dailyAmount undefined..1 https://fhir.kemkes.go.id/r4/StructureDefinition/SimpleQuantity "How to consume/day?" "Identifies the quantity expected to be consumed in a given day."
* activity.detail.dailyAmount ^requirements = "Allows rough dose checking."
* activity.detail.dailyAmount ^alias = "daily dose"
* activity.detail.quantity undefined..1 https://fhir.kemkes.go.id/r4/StructureDefinition/SimpleQuantity "How much to administer/supply/consume" "Identifies the quantity expected to be supplied, administered or consumed by the subject."
* activity.detail.description undefined..1 string "Extra info describing activity to perform" "This provides a textual description of constraints on the intended activity occurrence, including relation to other activities.  It may also include objectives, pre-conditions and end-conditions.  Finally, it may convey specifics about the activity such as body site, method, route, etc."
* note undefined..undefined Annotation "Comments about the plan" "General notes about the care plan not covered elsewhere."
* note ^requirements = "Used to capture information that applies to the plan as a whole that doesn't fit into discrete elements."