Resource: Coverage
Id: Coverage
Description: "Financial instrument which may be used to reimburse or pay for health care products and services. Includes both insurance and self-payment."
* ^meta.lastUpdated = "2024-04-03T07:18:46.5353275+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Financial.Support"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #fm
* ^status = #draft
* ^date = "2024-04-03T08:05:28.8219444+00:00"
* ^publisher = "Health Level Seven International (Financial Management)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/fm/index.cfm"
* ^purpose = "Coverage provides a link between covered parties (patients) and the payors of their healthcare costs (both insurance and self-pay)."
* . ^short = "Insurance or medical plan or a payment agreement"
* . ^definition = "Financial instrument which may be used to reimburse or pay for health care products and services. Includes both insurance and self-payment."
* . ^comment = "The Coverage resource contains the insurance card level information, which is customary to provide on claims and other communications between providers and insurers."
* extension contains primaryCareProvider 0..1
* extension[primaryCareProvider] ^type.code = "Extension"
* extension[primaryCareProvider] ^type.profile = "https://fhir.kemkes.go.id/r4/StructureDefinition/primaryCareProvider"
* extension[primaryCareProvider] ^isModifier = false
* identifier undefined..undefined SU Identifier "Business Identifier for the coverage" "A unique identifier assigned to this coverage."
* identifier ^comment = "The main (and possibly only) identifier for the coverage - often referred to as a Member Id, Certificate number, Personal Health Number or Case ID. May be constructed as the concatenation of the Coverage.SubscriberID and the Coverage.dependant."
* identifier ^requirements = "Allows coverages to be distinguished and referenced."
* status 1..1 ?! SU code "active | cancelled | draft | entered-in-error" "The status of the resource instance."
* status from http://hl7.org/fhir/ValueSet/fm-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains the code entered-in-error that marks the coverage as not currently valid."
* status ^requirements = "Need to track the status of the resource as 'draft' resources may undergo further edits while 'active' resources are immutable and may only have their status changed to 'cancelled'."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "CoverageStatus"
* status ^binding.description = "A code specifying the state of the resource instance."
* type undefined..1 SU CodeableConcept "Coverage category such as medical or accident" "The type of coverage: social program, medical plan, accident coverage (workers compensation, auto), group health or payment by an individual or organization."
* type from http://hl7.org/fhir/ValueSet/coverage-type (preferred)
* type ^requirements = "The order of application of coverages is dependent on the types of coverage."
* type ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* type ^binding.extension.valueString = "CoverageType"
* type ^binding.description = "The type of insurance: public health, worker compensation; private accident, auto, private health, etc.) or a direct payment by an individual or organization."
* policyHolder undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Owner of the policy" "The party who 'owns' the insurance policy."
* policyHolder ^comment = "For example: may be an individual, corporation or the subscriber's employer."
* policyHolder ^requirements = "This provides employer information in the case of Worker's Compensation and other policies."
* subscriber undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson) "Subscriber to the policy" "The party who has signed-up for or 'owns' the contractual relationship to the policy or to whom the benefit of the policy for services rendered to them or their family is due."
* subscriber ^comment = "May be self or a parent in the case of dependants."
* subscriber ^requirements = "This is the party who is entitled to the benfits under the policy."
* subscriberId undefined..1 SU string "ID assigned to the subscriber" "The insurer assigned ID for the Subscriber."
* subscriberId ^requirements = "The insurer requires this identifier on correspondance and claims (digital and otherwise)."
* beneficiary 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient) "Plan beneficiary" "The party who benefits from the insurance coverage; the patient when products and/or services are provided."
* beneficiary ^requirements = "This is the party who receives treatment for which the costs are reimbursed under the coverage."
* dependent undefined..1 SU string "Dependent number" "A unique identifier for a dependent under the coverage."
* dependent ^comment = "Periodically the member number is constructed from the subscriberId and the dependant number."
* dependent ^requirements = "For some coverages a single identifier is issued to the Subscriber and then a unique dependent number is issued to each beneficiary."
* relationship undefined..1 CodeableConcept "Beneficiary relationship to the subscriber" "The relationship of beneficiary (patient) to the subscriber."
* relationship from http://hl7.org/fhir/ValueSet/subscriber-relationship (extensible)
* relationship ^comment = "Typically, an individual uses policies which are theirs (relationship='self') before policies owned by others."
* relationship ^requirements = "To determine relationship between the patient and the subscriber to determine coordination of benefits."
* relationship ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* relationship ^binding.extension.valueString = "Relationship"
* relationship ^binding.description = "The relationship between the Subscriber and the Beneficiary (insured/covered party/patient)."
* period undefined..1 SU Period "Coverage start and end dates" "Time period during which the coverage is in force. A missing start date indicates the start date isn't known, a missing end date means the coverage is continuing to be in force."
* period ^requirements = "Some insurers require the submission of the coverage term."
* payor 1..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Organization or https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson) "Issuer of the policy" "The program or plan underwriter or payor including both insurance and non-insurance agreements, such as patient-pay agreements."
* payor ^comment = "May provide multiple identifiers such as insurance company identifier or business identifier (BIN number).\nFor selfpay it may provide multiple paying persons and/or organizations."
* payor ^requirements = "Need to identify the issuer to target for claim processing and for coordination of benefit processing."
* class undefined..undefined BackboneElement "Additional coverage classifications" "A suite of underwriter specific classifiers."
* class ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* class ^extension[=].valueString = "Class"
* class ^comment = "For example may be used to identify a class of coverage or employer group, Policy, Plan."
* class ^requirements = "The codes provided on the health card which identify or confirm the specific policy for the insurer."
* class.type 1..1 SU CodeableConcept "Type of class such as 'group' or 'plan'" "The type of classification for which an insurer-specific class label or number and optional name is provided, for example may be used to identify a class of coverage or employer group, Policy, Plan."
* class.type from http://hl7.org/fhir/ValueSet/coverage-class (extensible)
* class.type ^requirements = "The insurer issued label for a specific health card value."
* class.type ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* class.type ^binding.extension.valueString = "CoverageClass"
* class.type ^binding.description = "The policy classifications, eg. Group, Plan, Class, etc."
* class.value 1..1 SU string "Value associated with the type" "The alphanumeric string value associated with the insurer issued label."
* class.value ^comment = "For example, the Group or Plan number."
* class.value ^requirements = "The insurer issued label and value are necessary to identify the specific policy."
* class.name undefined..1 SU string "Human readable description of the type and value" "A short description for the class."
* class.name ^requirements = "Used to provide a meaningful description in correspondence to the patient."
* order undefined..1 SU positiveInt "Relative order of the coverage" "The order of applicability of this coverage relative to other coverages which are currently in force. Note, there may be gaps in the numbering and this does not imply primary, secondary etc. as the specific positioning of coverages depends upon the episode of care."
* order ^requirements = "Used in managing the coordination of benefits."
* network undefined..1 SU string "Insurer network" "The insurer-specific identifier for the insurer-defined network of providers to which the beneficiary may seek treatment which will be covered at the 'in-network' rate, otherwise 'out of network' terms and conditions apply."
* network ^requirements = "Used in referral for treatment and in claims processing."
* costToBeneficiary undefined..undefined BackboneElement "Patient payments for services/products" "A suite of codes indicating the cost category and associated amount which have been detailed in the policy and may have been  included on the health card."
* costToBeneficiary ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* costToBeneficiary ^extension[=].valueString = "CostToBeneficiary"
* costToBeneficiary ^comment = "For example by knowing the patient visit co-pay, the provider can collect the amount prior to undertaking treatment."
* costToBeneficiary ^requirements = "Required by providers to manage financial transaction with the patient."
* costToBeneficiary ^alias[0] = "CoPay"
* costToBeneficiary ^alias[+] = "Deductible"
* costToBeneficiary ^alias[+] = "Exceptions"
* costToBeneficiary.type undefined..1 SU CodeableConcept "Cost category" "The category of patient centric costs associated with treatment."
* costToBeneficiary.type from http://hl7.org/fhir/ValueSet/coverage-copay-type (extensible)
* costToBeneficiary.type ^comment = "For example visit, specialist visits, emergency, inpatient care, etc."
* costToBeneficiary.type ^requirements = "Needed to identify the category associated with the amount for the patient."
* costToBeneficiary.type ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* costToBeneficiary.type ^binding.extension.valueString = "CopayTypes"
* costToBeneficiary.type ^binding.description = "The types of services to which patient copayments are specified."
* costToBeneficiary.value[x] 1..1 SU https://fhir.kemkes.go.id/r4/StructureDefinition/SimpleQuantity or Money "The amount or percentage due from the beneficiary" "The amount due from the patient for the cost category."
* costToBeneficiary.value[x] ^comment = "Amount may be expressed as a percentage of the service/product cost or a fixed amount of currency."
* costToBeneficiary.value[x] ^requirements = "Needed to identify the amount for the patient associated with the category."
* costToBeneficiary.exception undefined..undefined BackboneElement "Exceptions for patient payments" "A suite of codes indicating exceptions or reductions to patient costs and their effective periods."
* costToBeneficiary.exception ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* costToBeneficiary.exception ^extension[=].valueString = "Exemption"
* costToBeneficiary.exception ^requirements = "Required by providers to manage financial transaction with the patient."
* costToBeneficiary.exception.type 1..1 SU CodeableConcept "Exception category" "The code for the specific exception."
* costToBeneficiary.exception.type from http://hl7.org/fhir/ValueSet/coverage-financial-exception (example)
* costToBeneficiary.exception.type ^requirements = "Needed to identify the exception associated with the amount for the patient."
* costToBeneficiary.exception.type ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* costToBeneficiary.exception.type ^binding.extension.valueString = "CoverageFinancialException"
* costToBeneficiary.exception.type ^binding.description = "The types of exceptions from the part or full value of financial obligations such as copays."
* costToBeneficiary.exception.period undefined..1 SU Period "The effective period of the exception" "The timeframe during when the exception is in force."
* costToBeneficiary.exception.period ^requirements = "Needed to identify the applicable timeframe for the exception for the correct calculation of patient costs."
* subrogation undefined..1 boolean "Reimbursement to insurer" "When 'subrogation=true' this insurance instance has been included not for adjudication but to provide insurers with the details to recover costs."
* subrogation ^comment = "Typically, automotive and worker's compensation policies would be flagged with 'subrogation=true' to enable healthcare payors to collect against accident claims."
* subrogation ^requirements = "See definition for when to be used."
* contract undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Contract) "Contract details" "The policy(s) which constitute this insurance coverage."
* contract ^requirements = "To reference the legally binding contract between the policy holder and the insurer."