Resource: FamilyMemberHistory
Id: FamilyMemberHistory
Description: "Significant health conditions for a person related to the patient relevant in the context of care for the patient."
* ^meta.lastUpdated = "2019-10-31T22:29:23.356+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Clinical.Summary"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #pc
* ^status = #draft
* ^date = "2023-05-12T03:54:04.8907436+00:00"
* ^publisher = "Health Level Seven International (Patient Care)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/patientcare/index.cfm"
* obeys fhs-2 and fhs-1
* . ^short = "Information about patient's relatives, relevant for patient"
* . ^definition = "Significant health conditions for a person related to the patient relevant in the context of care for the patient."
* identifier 0..* SU Identifier "External Id(s) for this record" "Business identifiers assigned to this family member history by the performer or other systems which remain constant as the resource is updated and propagates from server to server."
* identifier ^comment = "This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number."
* identifier ^requirements = "Allows identification of the family member history as it is known by various participating systems and in a way that remains consistent across servers."
* instantiatesCanonical 0..* SU Canonical(https://fhir.kemkes.go.id/r4/StructureDefinition/PlanDefinition or https://fhir.kemkes.go.id/r4/StructureDefinition/Questionnaire or https://fhir.kemkes.go.id/r4/StructureDefinition/ActivityDefinition or https://fhir.kemkes.go.id/r4/StructureDefinition/Measure or https://fhir.kemkes.go.id/r4/StructureDefinition/OperationDefinition) "Instantiates FHIR protocol or definition" "The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this FamilyMemberHistory."
* instantiatesUri 0..* SU uri "Instantiates external protocol or definition" "The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this FamilyMemberHistory."
* instantiatesUri ^comment = "This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier."
* status 1..1 ?! SU code "partial | completed | entered-in-error | health-unknown" "A code specifying the status of the record of the family history of a specific family member."
* status from http://hl7.org/fhir/ValueSet/history-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "FamilyHistoryStatus"
* status ^binding.description = "A code that identifies the status of the family history record."
* dataAbsentReason 0..1 SU CodeableConcept "subject-unknown | withheld | unable-to-obtain | deferred" "Describes why the family member's history is not available."
* dataAbsentReason from http://hl7.org/fhir/ValueSet/history-absent-reason (example)
* dataAbsentReason ^requirements = "This is a separate element to allow it to have a distinct binding from reasonCode."
* dataAbsentReason ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* dataAbsentReason ^binding.extension.valueString = "FamilyHistoryAbsentReason"
* dataAbsentReason ^binding.description = "Codes describing the reason why a family member's history is not available."
* patient 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient) "Patient history is about" "The person who this history concerns."
* patient ^alias = "Proband"
* date 0..1 SU dateTime "When history was recorded or last updated" "The date (and possibly time) when the family member history was recorded or last updated."
* date ^comment = "This should be captured even if the same as the date on the List aggregating the full family history."
* date ^requirements = "Allows determination of how current the summary is."
* name 0..1 SU string "The family member described" "This will either be a name or a description; e.g. \"Aunt Susan\", \"my cousin with the red hair\"."
* name ^requirements = "Allows greater ease in ensuring the same person is being talked about."
* relationship 1..1 SU CodeableConcept "Relationship to the subject" "The type of relationship this person has to the patient (father, mother, brother etc.)."
* relationship from http://terminology.hl7.org/ValueSet/v3-FamilyMember (example)
* relationship ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* relationship ^binding.extension.valueString = "FamilialRelationship"
* relationship ^binding.description = "The nature of the relationship between the patient and the related person being described in the family member history."
* sex 0..1 SU CodeableConcept "male | female | other | unknown" "The birth sex of the family member."
* sex from http://hl7.org/fhir/ValueSet/administrative-gender (extensible)
* sex ^comment = "This element should ideally reflect whether the individual is genetically male or female.  However, as reported information based on the knowledge of the patient or reporting friend/relative, there may be situations where the reported sex might not be totally accurate.  E.g. 'Aunt Sue' might be XY rather than XX.  Questions soliciting this information should be phrased to encourage capture of genetic sex where known.  However, systems performing analysis should also allow for the possibility of imprecision with this element."
* sex ^requirements = "Not all relationship codes imply sex and the relative's sex can be relevant for risk assessments."
* sex ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* sex ^binding.extension.valueString = "Sex"
* sex ^binding.description = "Codes describing the sex assigned at birth as documented on the birth registration."
* born[x] 0..1 Period or date or string "(approximate) date of birth" "The actual or approximate date of birth of the relative."
* born[x] ^requirements = "Allows calculation of the relative's age."
* born[x] ^condition = "fhs-1"
* age[x] 0..1 SU Age or Range or string "(approximate) age" "The age of the relative at the time the family member history is recorded."
* age[x] ^comment = "use estimatedAge to indicate whether the age is actual or not."
* age[x] ^requirements = "While age can be calculated from date of birth, sometimes recording age directly is more natural for clinicians."
* age[x] ^condition = "fhs-1"
* estimatedAge 0..1 SU boolean "Age is estimated?" "If true, indicates that the age value specified is an estimated value."
* estimatedAge ^comment = "This element is labeled as a modifier because the fact that age is estimated can/should change the results of any algorithm that calculates based on the specified age."
* estimatedAge ^requirements = "Clinicians often prefer to specify an estimaged age rather than an age range."
* estimatedAge ^meaningWhenMissing = "It is unknown whether the age is an estimate or not"
* estimatedAge ^condition = "fhs-2"
* deceased[x] 0..1 SU boolean or Age or Range or date or string "Dead? How old/when?" "Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record."
* reasonCode 0..* SU CodeableConcept "Why was family member history performed?" "Describes why the family member history occurred in coded or textual form."
* reasonCode from http://hl7.org/fhir/ValueSet/clinical-findings (example)
* reasonCode ^comment = "Textual reasons can be captured using reasonCode.text."
* reasonCode ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* reasonCode ^binding.extension.valueString = "FamilyHistoryReason"
* reasonCode ^binding.description = "Codes indicating why the family member history was done."
* reasonReference 0..* SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Condition or https://fhir.kemkes.go.id/r4/StructureDefinition/Observation or https://fhir.kemkes.go.id/r4/StructureDefinition/AllergyIntolerance or https://fhir.kemkes.go.id/r4/StructureDefinition/QuestionnaireResponse or https://fhir.kemkes.go.id/r4/StructureDefinition/DiagnosticReport or https://fhir.kemkes.go.id/r4/StructureDefinition/DocumentReference) "Why was family member history performed?" "Indicates a Condition, Observation, AllergyIntolerance, or QuestionnaireResponse that justifies this family member history event."
* note 0..* Annotation "General note about related person" "This property allows a non condition-specific note to the made about the related person. Ideally, the note would be in the condition property, but this is not always possible."
* condition 0..* BackboneElement "Condition that the related person had" "The significant Conditions (or condition) that the family member had. This is a repeating section to allow a system to represent more than one condition per resource, though there is nothing stopping multiple resources - one per condition."
* condition.code 1..1 CodeableConcept "Condition suffered by relation" "The actual condition specified. Could be a coded condition (like MI or Diabetes) or a less specific string like 'cancer' depending on how much is known about the condition and the capabilities of the creating system."
* condition.code from http://hl7.org/fhir/ValueSet/condition-code (example)
* condition.code ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* condition.code ^binding.extension.valueString = "ConditionCode"
* condition.code ^binding.description = "Identification of the Condition or diagnosis."
* condition.outcome 0..1 CodeableConcept "deceased | permanent disability | etc." "Indicates what happened following the condition.  If the condition resulted in death, deceased date is captured on the relation."
* condition.outcome from http://hl7.org/fhir/ValueSet/condition-outcome (example)
* condition.outcome ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* condition.outcome ^binding.extension.valueString = "ConditionOutcome"
* condition.outcome ^binding.description = "The result of the condition for the patient; e.g. death, permanent disability, temporary disability, etc."
* condition.contributedToDeath 0..1 boolean "Whether the condition contributed to the cause of death" "This condition contributed to the cause of death of the related person. If contributedToDeath is not populated, then it is unknown."
* condition.onset[x] 0..1 Age or Range or Period or string "When condition first manifested" "Either the age of onset, range of approximate age or descriptive string can be recorded.  For conditions with multiple occurrences, this describes the first known occurrence."
* condition.onset[x] ^requirements = "Age of onset of a condition in relatives is predictive of risk for the patient."
* condition.note 0..* Annotation "Extra information about condition" "An area where general notes can be placed about this specific condition."