Resource: MedicationStatement
Id: MedicationStatement
Description: """A record of a medication that is being consumed by a patient.   A MedicationStatement may indicate that the patient may be taking the medication now or has taken the medication in the past or will be taking the medication in the future.  The source of this information can be the patient, significant other (such as a family member or spouse), or a clinician.  A common scenario where this information is captured is during the history taking process during a patient visit or stay.   The medication information may come from sources such as the patient's memory, from a prescription bottle,  or from a list of medications the patient, clinician or other party maintains. 

The primary difference between a medication statement and a medication administration is that the medication administration has complete administration information and is based on actual administration information from the person who administered the medication.  A medication statement is often, if not always, less specific.  There is no required date/time when the medication was administered, in fact we only know that a source has reported the patient is taking this medication, where details such as time, quantity, or rate or even medication product may be incomplete or missing or less precise.  As stated earlier, the medication statement information may come from the patient's memory, from a prescription bottle or from a list of medications the patient, clinician or other party maintains.  Medication administration is more formal and is not missing detailed information."""
* ^meta.lastUpdated = "2019-10-31T22:29:23.356+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Clinical.Medications"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 3
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #phx
* ^status = #draft
* ^date = "2023-05-12T03:54:04.8907436+00:00"
* ^publisher = "Health Level Seven International (Pharmacy)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/medication/index.cfm"
* . ^short = "Record of medication being taken by a patient"
* . ^definition = "A record of a medication that is being consumed by a patient.   A MedicationStatement may indicate that the patient may be taking the medication now or has taken the medication in the past or will be taking the medication in the future.  The source of this information can be the patient, significant other (such as a family member or spouse), or a clinician.  A common scenario where this information is captured is during the history taking process during a patient visit or stay.   The medication information may come from sources such as the patient's memory, from a prescription bottle,  or from a list of medications the patient, clinician or other party maintains. \n\nThe primary difference between a medication statement and a medication administration is that the medication administration has complete administration information and is based on actual administration information from the person who administered the medication.  A medication statement is often, if not always, less specific.  There is no required date/time when the medication was administered, in fact we only know that a source has reported the patient is taking this medication, where details such as time, quantity, or rate or even medication product may be incomplete or missing or less precise.  As stated earlier, the medication statement information may come from the patient's memory, from a prescription bottle or from a list of medications the patient, clinician or other party maintains.  Medication administration is more formal and is not missing detailed information."
* . ^comment = "When interpreting a medicationStatement, the value of the status and NotTaken needed to be considered:\rMedicationStatement.status + MedicationStatement.wasNotTaken\rStatus=Active + NotTaken=T = Not currently taking\rStatus=Completed + NotTaken=T = Not taken in the past\rStatus=Intended + NotTaken=T = No intention of taking\rStatus=Active + NotTaken=F = Taking, but not as prescribed\rStatus=Active + NotTaken=F = Taking\rStatus=Intended +NotTaken= F = Will be taking (not started)\rStatus=Completed + NotTaken=F = Taken in past\rStatus=In Error + NotTaken=N/A = In Error."
* identifier undefined..undefined SU Identifier "External identifier" "Identifiers associated with this Medication Statement that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate. They are business identifiers assigned to this resource by the performer or other systems and remain constant as the resource is updated and propagates from server to server."
* identifier ^comment = "This is a business identifier, not a resource identifier."
* basedOn undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/MedicationRequest or https://fhir.kemkes.go.id/r4/StructureDefinition/CarePlan or https://fhir.kemkes.go.id/r4/StructureDefinition/ServiceRequest) "Fulfils plan, proposal or order" "A plan, proposal or order that is fulfilled in whole or in part by this event."
* basedOn ^requirements = "Allows tracing of authorization for the event and tracking whether proposals/recommendations were acted upon."
* partOf undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/MedicationAdministration or https://fhir.kemkes.go.id/r4/StructureDefinition/MedicationDispense or https://fhir.kemkes.go.id/r4/StructureDefinition/MedicationStatement or https://fhir.kemkes.go.id/r4/StructureDefinition/Procedure or https://fhir.kemkes.go.id/r4/StructureDefinition/Observation) "Part of referenced event" "A larger event of which this particular event is a component or step."
* partOf ^requirements = "This should not be used when indicating which resource a MedicationStatement has been derived from.  If that is the use case, then MedicationStatement.derivedFrom should be used."
* status 1..1 ?! SU code "active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken" "A code representing the patient or other source's judgment about the state of the medication used that this statement is about.  Generally, this will be active or completed."
* status from http://hl7.org/fhir/ValueSet/medication-statement-status|4.0.1 (required)
* status ^comment = "MedicationStatement is a statement at a point in time.  The status is only representative at the point when it was asserted.  The value set for MedicationStatement.status contains codes that assert the status of the use of the medication by the patient (for example, stopped or on hold) as well as codes that assert the status of the medication statement itself (for example, entered in error).\r\rThis element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "MedicationStatementStatus"
* status ^binding.description = "A coded concept indicating the current status of a MedicationStatement."
* statusReason undefined..undefined CodeableConcept "Reason for current status" "Captures the reason for the current state of the MedicationStatement."
* statusReason from http://hl7.org/fhir/ValueSet/reason-medication-status-codes (example)
* statusReason ^comment = "This is generally only used for \"exception\" statuses such as \"not-taken\", \"on-hold\", \"cancelled\" or \"entered-in-error\". The reason for performing the event at all is captured in reasonCode, not here."
* statusReason ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* statusReason ^binding.extension.valueString = "MedicationStatementStatusReason"
* statusReason ^binding.description = "A coded concept indicating the reason for the status of the statement."
* category undefined..1 SU CodeableConcept "Type of medication usage" "Indicates where the medication is expected to be consumed or administered."
* category from http://hl7.org/fhir/ValueSet/medication-statement-category (preferred)
* category ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* category ^binding.extension.valueString = "MedicationStatementCategory"
* category ^binding.description = "A coded concept identifying where the medication included in the MedicationStatement is expected to be consumed or administered."
* medication[x] 1..1 SU CodeableConcept or Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Medication) "What medication was taken" "Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications."
* medication[x] from http://hl7.org/fhir/ValueSet/medication-codes (example)
* medication[x] ^comment = "If only a code is specified, then it needs to be a code for a specific product. If more information is required, then the use of the medication resource is recommended.  For example, if you require form or lot number, then you must reference the Medication resource."
* medication[x] ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* medication[x] ^binding.extension.valueString = "MedicationCode"
* medication[x] ^binding.description = "A coded concept identifying the substance or product being taken."
* subject 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Group) "Who is/was taking  the medication" "The person, animal or group who is/was taking the medication."
* context undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Encounter or https://fhir.kemkes.go.id/r4/StructureDefinition/EpisodeOfCare) "Encounter / Episode associated with MedicationStatement" "The encounter or episode of care that establishes the context for this MedicationStatement."
* effective[x] undefined..1 SU dateTime or Period "The date/time or interval when the medication is/was/will be taken" "The interval of time during which it is being asserted that the patient is/was/will be taking the medication (or was not taking, when the MedicationStatement.taken element is No)."
* effective[x] ^comment = "This attribute reflects the period over which the patient consumed the medication and is expected to be populated on the majority of Medication Statements. If the medication is still being taken at the time the statement is recorded, the \"end\" date will be omitted.  The date/time attribute supports a variety of dates - year, year/month and exact date.  If something more than this is required, this should be conveyed as text."
* dateAsserted undefined..1 SU dateTime "When the statement was asserted?" "The date when the medication statement was asserted by the information source."
* informationSource undefined..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Person or organization that provided the information about the taking of this medication" "The person or organization that provided the information about the taking of this medication. Note: Use derivedFrom when a MedicationStatement is derived from other resources, e.g. Claim or MedicationRequest."
* derivedFrom undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "Additional supporting information" "Allows linking the MedicationStatement to the underlying MedicationRequest, or to other information that supports or is used to derive the MedicationStatement."
* derivedFrom ^comment = "Likely references would be to MedicationRequest, MedicationDispense, Claim, Observation or QuestionnaireAnswers.  The most common use cases for deriving a MedicationStatement comes from creating a MedicationStatement from a MedicationRequest or from a lab observation or a claim.  it should be noted that the amount of information that is available varies from the type resource that you derive the MedicationStatement from."
* reasonCode undefined..undefined CodeableConcept "Reason for why the medication is being/was taken" "A reason for why the medication is being/was taken."
* reasonCode from http://hl7.org/fhir/ValueSet/condition-code (example)
* reasonCode ^comment = "This could be a diagnosis code. If a full condition record exists or additional detail is needed, use reasonForUseReference."
* reasonCode ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* reasonCode ^binding.extension.valueString = "MedicationReason"
* reasonCode ^binding.description = "A coded concept identifying why the medication is being taken."
* reasonReference undefined..undefined Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Condition or https://fhir.kemkes.go.id/r4/StructureDefinition/Observation or https://fhir.kemkes.go.id/r4/StructureDefinition/DiagnosticReport) "Condition or observation that supports why the medication is being/was taken" "Condition or observation that supports why the medication is being/was taken."
* reasonReference ^comment = "This is a reference to a condition that is the reason why the medication is being/was taken.  If only a code exists, use reasonForUseCode."
* note undefined..undefined Annotation "Further information about the statement" "Provides extra information about the medication statement that is not conveyed by the other attributes."
* dosage undefined..undefined Dosage "Details of how medication is/was taken or should be taken" "Indicates how the medication is/was or should be taken by the patient."
* dosage ^comment = "The dates included in the dosage on a Medication Statement reflect the dates for a given dose.  For example, \"from November 1, 2016 to November 3, 2016, take one tablet daily and from November 4, 2016 to November 7, 2016, take two tablets daily.\"  It is expected that this specificity may only be populated where the patient brings in their labeled container or where the Medication Statement is derived from a MedicationRequest."