Resource: CoverageEligibilityResponse
Id: CoverageEligibilityResponse
Description: "This resource provides eligibility and plan details from the processing of an CoverageEligibilityRequest resource."
* ^meta.lastUpdated = "2024-04-26T18:58:54.5034934+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Financial.Support"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #fm
* ^status = #draft
* ^date = "2024-04-28T07:56:56.6589413+00:00"
* ^publisher = "Health Level Seven International (Financial Management)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/fm/index.cfm"
* . ^short = "CoverageEligibilityResponse resource"
* . ^definition = "This resource provides eligibility and plan details from the processing of an CoverageEligibilityRequest resource."
* extension contains policyClass 0..*
* extension[policyClass] ^type.code = "Extension"
* extension[policyClass] ^type.profile = "https://fhir.kemkes.go.id/r4/StructureDefinition/PolicyClass"
* extension[policyClass] ^isModifier = false
* extension contains eligibilityStatus 0..*
* extension[eligibilityStatus] ^type.code = "Extension"
* extension[eligibilityStatus] ^type.profile = "https://fhir.kemkes.go.id/r4/StructureDefinition/EligibilityStatus"
* extension[eligibilityStatus] ^isModifier = false
* identifier undefined..undefined Identifier "Business Identifier for coverage eligiblity request" "A unique identifier assigned to this coverage eligiblity request."
* identifier ^requirements = "Allows coverage eligibility requests to be distinguished and referenced."
* status 1..1 ?! SU code "active | cancelled | draft | entered-in-error" "The status of the resource instance."
* status from http://hl7.org/fhir/ValueSet/fm-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."
* status ^requirements = "Need to track the status of the resource as 'draft' resources may undergo further edits while 'active' resources are immutable and may only have their status changed to 'cancelled'."
* status ^isModifierReason = "This element is labeled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension[=].valueString = "EligibilityResponseStatus"
* status ^binding.description = "A code specifying the state of the resource instance."
* purpose 1..undefined SU code "auth-requirements | benefits | discovery | validation" "Code to specify whether requesting: prior authorization requirements for some service categories or billing codes; benefits for coverages specified or discovered; discovery and return of coverages for the patient; and/or validation that the specified coverage is in-force at the date/period specified or 'now' if not specified."
* purpose from http://hl7.org/fhir/ValueSet/eligibilityresponse-purpose|4.0.1 (required)
* purpose ^requirements = "To indicate the processing actions requested."
* purpose ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* purpose ^binding.extension[=].valueString = "EligibilityResponsePurpose"
* purpose ^binding.description = "A code specifying the types of information being requested."
* patient 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient) "Intended recipient of products and services" "The party who is the beneficiary of the supplied coverage and for whom eligibility is sought."
* patient ^requirements = "Required to provide context and coverage validation."
* serviced[x] undefined..1 date or Period "Estimated date or dates of service" "The date or dates when the enclosed suite of services were performed or completed."
* serviced[x] ^requirements = "Required to provide time context for the request."
* created 1..1 SU dateTime "Response creation date" "The date this resource was created."
* created ^requirements = "Need to record a timestamp for use by both the recipient and the issuer."
* requestor undefined..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Party responsible for the request" "The provider which is responsible for the request."
* requestor ^comment = "Typically this field would be 1..1 where this party is responsible for the claim but not necessarily professionally responsible for the provision of the individual products and services listed below."
* request 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/CoverageEligibilityRequest) "Eligibility request reference" "Reference to the original request resource."
* request ^requirements = "Needed to allow the response to be linked to the request."
* outcome 1..1 SU code "queued | complete | error | partial" "The outcome of the request processing."
* outcome from http://hl7.org/fhir/ValueSet/remittance-outcome|4.0.1 (required)
* outcome ^comment = "The resource may be used to indicate that: the request has been held (queued) for processing; that it has been processed and errors found (error); that no errors were found and that some of the adjudication has been undertaken (partial) or that all of the adjudication has been undertaken (complete)."
* outcome ^requirements = "To advise the requestor of an overall processing outcome."
* outcome ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* outcome ^binding.extension[=].valueString = "RemittanceOutcome"
* outcome ^binding.extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-isCommonBinding"
* outcome ^binding.extension[=].valueBoolean = true
* outcome ^binding.description = "The outcome of the processing."
* disposition undefined..1 string "Disposition Message" "A human readable description of the status of the adjudication."
* disposition ^requirements = "Provided for user display."
* insurer 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Coverage issuer" "The Insurer who issued the coverage in question and is the author of the response."
* insurer ^requirements = "Need to identify the author."
* insurance undefined..undefined BackboneElement "Patient insurance information" "Financial instruments for reimbursement for the health care products and services."
* insurance ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-display-hint"
* insurance ^extension[=].valueString = "380;0"
* insurance ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* insurance ^extension[=].valueString = "Insurance"
* insurance ^comment = "All insurance coverages for the patient which may be applicable for reimbursement, of the products and services listed in the claim, are typically provided in the claim to allow insurers to confirm the ordering of the insurance coverages relative to local 'coordination of benefit' rules. One coverage (and only one) with 'focal=true' is to be used in the adjudication of this claim. Coverages appearing before the focal Coverage in the list, and where 'subrogation=false', should provide a reference to the ClaimResponse containing the adjudication results of the prior claim."
* insurance ^requirements = "There must be at least one coverage for which eligibility is requested."
* insurance.coverage 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Coverage) "Insurance information" "Reference to the insurance card level information contained in the Coverage resource. The coverage issuing insurer will use these details to locate the patient's actual coverage within the insurer's information system."
* insurance.coverage ^requirements = "Required to allow the adjudicator to locate the correct policy and history within their information system."
* insurance.inforce undefined..1 boolean "Coverage inforce indicator" "Flag indicating if the coverage provided is inforce currently if no service date(s) specified or for the whole duration of the service dates."
* insurance.inforce ^requirements = "Needed to convey the answer to the eligibility validation request."
* insurance.benefitPeriod undefined..1 Period "When the benefits are applicable" "The term of the benefits documented in this response."
* insurance.benefitPeriod ^requirements = "Needed as coverages may be multi-year while benefits tend to be annual therefore a separate expression of the benefit period is needed."
* insurance.item undefined..undefined BackboneElement "Benefits and authorization details" "Benefits and optionally current balances, and authorization details by category or service."
* insurance.item obeys ces-1
* insurance.item ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-display-hint"
* insurance.item ^extension[=].valueString = "340;120"
* insurance.item ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* insurance.item ^extension[=].valueString = "Items"
* insurance.item.category undefined..1 CodeableConcept "Benefit classification" "Code to identify the general type of benefits under which products and services are provided."
* insurance.item.category from http://hl7.org/fhir/ValueSet/ex-benefitcategory (example)
* insurance.item.category ^comment = "Examples include Medical Care, Periodontics, Renal Dialysis, Vision Coverage."
* insurance.item.category ^requirements = "Needed to convey the category of service or product for which eligibility is sought."
* insurance.item.category ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.category ^binding.extension[=].valueString = "BenefitCategory"
* insurance.item.category ^binding.description = "Benefit categories such as: oral, medical, vision etc."
* insurance.item.productOrService undefined..1 CodeableConcept "Billing, service, product, or drug code" "This contains the product, service, drug or other billing code for the item."
* insurance.item.productOrService from http://hl7.org/fhir/ValueSet/service-uscls (example)
* insurance.item.productOrService ^comment = "Code to indicate the Professional Service or Product supplied (e.g. CTP, HCPCS, USCLS, ICD10, NCPDP, DIN, RxNorm, ACHI, CCI)."
* insurance.item.productOrService ^requirements = "Needed to convey the actual service or product for which eligibility is sought."
* insurance.item.productOrService ^alias[0] = "Drug Code"
* insurance.item.productOrService ^alias[+] = "Bill Code"
* insurance.item.productOrService ^alias[+] = "Service Code"
* insurance.item.productOrService ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.productOrService ^binding.extension[=].valueString = "ServiceProduct"
* insurance.item.productOrService ^binding.description = "Allowable service and product codes."
* insurance.item.modifier undefined..undefined CodeableConcept "Product or service billing modifiers" "Item typification or modifiers codes to convey additional context for the product or service."
* insurance.item.modifier from http://hl7.org/fhir/ValueSet/claim-modifiers (example)
* insurance.item.modifier ^comment = "For example in Oral whether the treatment is cosmetic or associated with TMJ, or for Medical whether the treatment was outside the clinic or out of office hours."
* insurance.item.modifier ^requirements = "To support provision of the item or to charge an elevated fee."
* insurance.item.modifier ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.modifier ^binding.extension[=].valueString = "Modifiers"
* insurance.item.modifier ^binding.description = "Item type or modifiers codes, eg for Oral whether the treatment is cosmetic or associated with TMJ, or an appliance was lost or stolen."
* insurance.item.provider undefined..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole) "Performing practitioner" "The practitioner who is eligible for the provision of the product or service."
* insurance.item.provider ^requirements = "Needed to convey the eligible provider."
* insurance.item.excluded undefined..1 boolean "Excluded from the plan" "True if the indicated class of service is excluded from the plan, missing or False indicates the product or service is included in the coverage."
* insurance.item.excluded ^requirements = "Needed to identify items that are specifically excluded from the coverage."
* insurance.item.name undefined..1 string "Short name for the benefit" "A short name or tag for the benefit."
* insurance.item.name ^comment = "For example: MED01, or DENT2."
* insurance.item.name ^requirements = "Required to align with other plan names."
* insurance.item.description undefined..1 string "Description of the benefit or services covered" "A richer description of the benefit or services covered."
* insurance.item.description ^comment = "For example 'DENT2 covers 100% of basic, 50% of major but excludes Ortho, Implants and Cosmetic services'."
* insurance.item.description ^requirements = "Needed for human readable reference."
* insurance.item.network undefined..1 CodeableConcept "In or out of network" "Is a flag to indicate whether the benefits refer to in-network providers or out-of-network providers."
* insurance.item.network from http://hl7.org/fhir/ValueSet/benefit-network (example)
* insurance.item.network ^requirements = "Needed as in or out of network providers are treated differently under the coverage."
* insurance.item.network ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.network ^binding.extension[=].valueString = "BenefitNetwork"
* insurance.item.network ^binding.description = "Code to classify in or out of network services."
* insurance.item.unit undefined..1 CodeableConcept "Individual or family" "Indicates if the benefits apply to an individual or to the family."
* insurance.item.unit from http://hl7.org/fhir/ValueSet/benefit-unit (example)
* insurance.item.unit ^requirements = "Needed for the understanding of the benefits."
* insurance.item.unit ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.unit ^binding.extension[=].valueString = "BenefitUnit"
* insurance.item.unit ^binding.description = "Unit covered/serviced - individual or family."
* insurance.item.term undefined..1 CodeableConcept "Annual or lifetime" "The term or period of the values such as 'maximum lifetime benefit' or 'maximum annual visits'."
* insurance.item.term from http://hl7.org/fhir/ValueSet/benefit-term (example)
* insurance.item.term ^requirements = "Needed for the understanding of the benefits."
* insurance.item.term ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.term ^binding.extension[=].valueString = "BenefitTerm"
* insurance.item.term ^binding.description = "Coverage unit - annual, lifetime."
* insurance.item.benefit undefined..undefined BackboneElement "Benefit Summary" "Benefits used to date."
* insurance.item.benefit ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-display-hint"
* insurance.item.benefit ^extension[=].valueString = "340;320"
* insurance.item.benefit ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* insurance.item.benefit ^extension[=].valueString = "Benefit"
* insurance.item.benefit.type 1..1 CodeableConcept "Benefit classification" "Classification of benefit being provided."
* insurance.item.benefit.type from http://hl7.org/fhir/ValueSet/benefit-type (example)
* insurance.item.benefit.type ^comment = "For example: deductible, visits, benefit amount."
* insurance.item.benefit.type ^requirements = "Needed to convey the nature of the benefit."
* insurance.item.benefit.type ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.benefit.type ^binding.extension[=].valueString = "BenefitType"
* insurance.item.benefit.type ^binding.description = "Deductable, visits, co-pay, etc."
* insurance.item.benefit.allowed[x] undefined..1 unsignedInt or string or Money "Benefits allowed" "The quantity of the benefit which is permitted under the coverage."
* insurance.item.benefit.allowed[x] ^requirements = "Needed to convey the benefits offered under the coverage."
* insurance.item.benefit.used[x] undefined..1 unsignedInt or string or Money "Benefits used" "The quantity of the benefit which have been consumed to date."
* insurance.item.benefit.used[x] ^requirements = "Needed to convey the benefits consumed to date."
* insurance.item.authorizationRequired undefined..1 boolean "Authorization required flag" "A boolean flag indicating whether a preauthorization is required prior to actual service delivery."
* insurance.item.authorizationRequired ^requirements = "Needed to convey that preauthorization is required."
* insurance.item.authorizationSupporting undefined..undefined CodeableConcept "Type of required supporting materials" "Codes or comments regarding information or actions associated with the preauthorization."
* insurance.item.authorizationSupporting from http://hl7.org/fhir/ValueSet/coverageeligibilityresponse-ex-auth-support (example)
* insurance.item.authorizationSupporting ^requirements = "Needed to inform the provider of collateral materials or actions needed for preauthorization."
* insurance.item.authorizationSupporting ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* insurance.item.authorizationSupporting ^binding.extension[=].valueString = "AuthSupporting"
* insurance.item.authorizationSupporting ^binding.description = "Type of supporting information to provide with a preauthorization."
* insurance.item.authorizationUrl undefined..1 uri "Preauthorization requirements endpoint" "A web location for obtaining requirements or descriptive information regarding the preauthorization."
* insurance.item.authorizationUrl ^requirements = "Needed to enable insurers to advise providers of informative information."
* preAuthRef undefined..1 string "Preauthorization reference" "A reference from the Insurer to which these services pertain to be used on further communication and as proof that the request occurred."
* preAuthRef ^requirements = "To provide any preauthorization reference for provider use."
* form undefined..1 CodeableConcept "Printed form identifier" "A code for the form to be used for printing the content."
* form from http://hl7.org/fhir/ValueSet/forms (example)
* form ^comment = "May be needed to identify specific jurisdictional forms."
* form ^requirements = "Needed to specify the specific form used for producing output for this response."
* form ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* form ^binding.extension[=].valueString = "Forms"
* form ^binding.extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-isCommonBinding"
* form ^binding.extension[=].valueBoolean = true
* form ^binding.description = "The forms codes."
* error undefined..undefined BackboneElement "Processing errors" "Errors encountered during the processing of the request."
* error ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* error ^extension[=].valueString = "Errors"
* error ^requirements = "Need to communicate processing issues to the requestor."
* error.code 1..1 CodeableConcept "Error code detailing processing issues" "An error code,from a specified code system, which details why the eligibility check could not be performed."
* error.code from http://hl7.org/fhir/ValueSet/adjudication-error (example)
* error.code ^requirements = "Required to convey processing errors."
* error.code ^binding.extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* error.code ^binding.extension[=].valueString = "AdjudicationError"
* error.code ^binding.extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-isCommonBinding"
* error.code ^binding.extension[=].valueBoolean = true
* error.code ^binding.description = "The error codes for adjudication processing."