Resource: CoverageEligibilityRequest
Id: CoverageEligibilityRequest
Description: "The CoverageEligibilityRequest provides patient and insurance coverage information to an insurer for them to respond, in the form of an CoverageEligibilityResponse, with information regarding whether the stated coverage is valid and in-force and optionally to provide the insurance details of the policy."
* ^meta.lastUpdated = "2019-10-31T22:29:23.356+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Financial.Support"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 2
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #fm
* ^status = #draft
* ^date = "2023-06-14T05:09:25.2943281+00:00"
* ^publisher = "Health Level Seven International (Financial Management)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/fm/index.cfm"
* . ^short = "CoverageEligibilityRequest resource"
* . ^definition = "The CoverageEligibilityRequest provides patient and insurance coverage information to an insurer for them to respond, in the form of an CoverageEligibilityResponse, with information regarding whether the stated coverage is valid and in-force and optionally to provide the insurance details of the policy."
* identifier 0..* Identifier "Business Identifier for coverage eligiblity request" "A unique identifier assigned to this coverage eligiblity request."
* identifier ^requirements = "Allows coverage eligibility requests to be distinguished and referenced."
* status 1..1 ?! SU code "active | cancelled | draft | entered-in-error" "The status of the resource instance."
* status from http://hl7.org/fhir/ValueSet/fm-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."
* status ^requirements = "Need to track the status of the resource as 'draft' resources may undergo further edits while 'active' resources are immutable and may only have their status changed to 'cancelled'."
* status ^isModifierReason = "This element is labeled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "EligibilityRequestStatus"
* status ^binding.description = "A code specifying the state of the resource instance."
* priority 0..1 CodeableConcept "Desired processing priority" "When the requestor expects the processor to complete processing."
* priority from http://hl7.org/fhir/ValueSet/process-priority (example)
* priority ^requirements = "Needed to advise the prossesor on the urgency of the request."
* priority ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* priority ^binding.extension.valueString = "ProcessPriority"
* priority ^binding.description = "The timeliness with which processing is required: STAT, normal, Deferred."
* purpose 1..* SU code "auth-requirements | benefits | discovery | validation" "Code to specify whether requesting: prior authorization requirements for some service categories or billing codes; benefits for coverages specified or discovered; discovery and return of coverages for the patient; and/or validation that the specified coverage is in-force at the date/period specified or 'now' if not specified."
* purpose from http://hl7.org/fhir/ValueSet/eligibilityrequest-purpose|4.0.1 (required)
* purpose ^requirements = "To indicate the processing actions requested."
* purpose ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* purpose ^binding.extension.valueString = "EligibilityRequestPurpose"
* purpose ^binding.description = "A code specifying the types of information being requested."
* patient 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient) "Intended recipient of products and services" "The party who is the beneficiary of the supplied coverage and for whom eligibility is sought."
* patient ^comment = "1..1."
* patient ^requirements = "Required to provide context and coverage validation."
* serviced[x] 0..1 date or Period "Estimated date or dates of service" "The date or dates when the enclosed suite of services were performed or completed."
* serviced[x] ^requirements = "Required to provide time context for the request."
* created 1..1 SU dateTime "Creation date" "The date when this resource was created."
* created ^requirements = "Need to record a timestamp for use by both the recipient and the issuer."
* enterer 0..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole) "Author" "Person who created the request."
* enterer ^requirements = "Some jurisdictions require the contact information for personnel completing eligibility requests."
* provider 0..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Party responsible for the request" "The provider which is responsible for the request."
* provider ^comment = "Typically this field would be 1..1 where this party is responsible for the eligibility request but not necessarily professionally responsible for the provision of the individual products and services listed below."
* provider ^requirements = "Needed to identify the requestor."
* insurer 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Coverage issuer" "The Insurer who issued the coverage in question and is the recipient of the request."
* insurer ^requirements = "Need to identify the recipient."
* facility 0..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Location) "Servicing facility" "Facility where the services are intended to be provided."
* facility ^requirements = "Insurance adjudication can be dependant on where services were delivered."
* supportingInfo 0..* BackboneElement "Supporting information" "Additional information codes regarding exceptions, special considerations, the condition, situation, prior or concurrent issues."
* supportingInfo ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* supportingInfo ^extension[=].valueString = "SupportingInformation"
* supportingInfo ^comment = "Often there are multiple jurisdiction specific valuesets which are required."
* supportingInfo ^requirements = "Typically these information codes are required to support the services rendered or the adjudication of the services rendered."
* supportingInfo.sequence 1..1 positiveInt "Information instance identifier" "A number to uniquely identify supporting information entries."
* supportingInfo.sequence ^requirements = "Necessary to maintain the order of the supporting information items and provide a mechanism to link to claim details."
* supportingInfo.information 1..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "Data to be provided" "Additional data or information such as resources, documents, images etc. including references to the data or the actual inclusion of the data."
* supportingInfo.information ^comment = "Could be used to provide references to other resources, document. For example could contain a PDF in an Attachment of the Police Report for an Accident."
* supportingInfo.information ^requirements = "To convey the data content to be provided when the information is more than a simple code or period."
* supportingInfo.appliesToAll 0..1 boolean "Applies to all items" "The supporting materials are applicable for all detail items, product/servce categories and specific billing codes."
* supportingInfo.appliesToAll ^requirements = "Needed to convey that the information is universal to the request."
* insurance 0..* BackboneElement "Patient insurance information" "Financial instruments for reimbursement for the health care products and services."
* insurance ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* insurance ^extension[=].valueString = "Insurance"
* insurance ^comment = "All insurance coverages for the patient which may be applicable for reimbursement, of the products and services listed in the claim, are typically provided in the claim to allow insurers to confirm the ordering of the insurance coverages relative to local 'coordination of benefit' rules. One coverage (and only one) with 'focal=true' is to be used in the adjudication of this claim. Coverages appearing before the focal Coverage in the list, and where 'subrogation=false', should provide a reference to the ClaimResponse containing the adjudication results of the prior claim."
* insurance ^requirements = "There must be at least one coverage for which eligibility is requested."
* insurance.focal 0..1 boolean "Applicable coverage" "A flag to indicate that this Coverage is to be used for evaluation of this request when set to true."
* insurance.focal ^comment = "A patient may (will) have multiple insurance policies which provide reimburement for healthcare services and products. For example a person may also be covered by their spouse's policy and both appear in the list (and may be from the same insurer). This flag will be set to true for only one of the listed policies and that policy will be used for evaluating this request. Other requests would be created to request evaluation against the other listed policies."
* insurance.focal ^requirements = "To identify which coverage in the list is being used to evaluate this request."
* insurance.coverage 1..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Coverage) "Insurance information" "Reference to the insurance card level information contained in the Coverage resource. The coverage issuing insurer will use these details to locate the patient's actual coverage within the insurer's information system."
* insurance.coverage ^requirements = "Required to allow the adjudicator to locate the correct policy and history within their information system."
* insurance.businessArrangement 0..1 string "Additional provider contract number" "A business agreement number established between the provider and the insurer for special business processing purposes."
* insurance.businessArrangement ^requirements = "Providers may have multiple business arrangements with a given insurer and must supply the specific contract number for adjudication."
* item 0..* BackboneElement "Item to be evaluated for eligibiity" "Service categories or billable services for which benefit details and/or an authorization prior to service delivery may be required by the payor."
* item ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* item ^extension[=].valueString = "Details"
* item ^requirements = "The items to be processed for the request."
* item.supportingInfoSequence 0..* positiveInt "Applicable exception or supporting information" "Exceptions, special conditions and supporting information applicable for this service or product line."
* item.supportingInfoSequence ^requirements = "Needed to support or inform the consideration for eligibility."
* item.category 0..1 CodeableConcept "Benefit classification" "Code to identify the general type of benefits under which products and services are provided."
* item.category from http://hl7.org/fhir/ValueSet/ex-benefitcategory (example)
* item.category ^comment = "Examples include Medical Care, Periodontics, Renal Dialysis, Vision Coverage."
* item.category ^requirements = "Needed to convey the category of service or product for which eligibility is sought."
* item.category ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* item.category ^binding.extension.valueString = "BenefitCategory"
* item.category ^binding.description = "Benefit categories such as: oral, medical, vision etc."
* item.productOrService 0..1 CodeableConcept "Billing, service, product, or drug code" "This contains the product, service, drug or other billing code for the item."
* item.productOrService from http://hl7.org/fhir/ValueSet/service-uscls (example)
* item.productOrService ^comment = "Code to indicate the Professional Service or Product supplied (e.g. CTP, HCPCS, USCLS, ICD10, NCPDP, DIN, RxNorm, ACHI, CCI)."
* item.productOrService ^requirements = "Needed to convey the actual service or product for which eligibility is sought."
* item.productOrService ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* item.productOrService ^binding.extension.valueString = "ServiceProduct"
* item.productOrService ^binding.description = "Allowable service and product codes."
* item.modifier 0..* CodeableConcept "Product or service billing modifiers" "Item typification or modifiers codes to convey additional context for the product or service."
* item.modifier from http://hl7.org/fhir/ValueSet/claim-modifiers (example)
* item.modifier ^comment = "For example in Oral whether the treatment is cosmetic or associated with TMJ, or for Medical whether the treatment was outside the clinic or out of office hours."
* item.modifier ^requirements = "To support provision of the item or to charge an elevated fee."
* item.modifier ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* item.modifier ^binding.extension.valueString = "Modifiers"
* item.modifier ^binding.description = "Item type or modifiers codes, eg for Oral whether the treatment is cosmetic or associated with TMJ, or an appliance was lost or stolen."
* item.provider 0..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole) "Perfoming practitioner" "The practitioner who is responsible for the product or service to be rendered to the patient."
* item.provider ^requirements = "Needed to support the evaluation of the eligibility."
* item.quantity 0..1 https://fhir.kemkes.go.id/r4/StructureDefinition/SimpleQuantity "Count of products or services" "The number of repetitions of a service or product."
* item.quantity ^requirements = "Required when the product or service code does not convey the quantity provided."
* item.unitPrice 0..1 Money "Fee, charge or cost per item" "The amount charged to the patient by the provider for a single unit."
* item.unitPrice ^requirements = "Needed to support the evaluation of the eligibility."
* item.facility 0..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Location or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Servicing facility" "Facility where the services will be provided."
* item.facility ^requirements = "Needed to support the evaluation of the eligibility."
* item.diagnosis 0..* BackboneElement "Applicable diagnosis" "Patient diagnosis for which care is sought."
* item.diagnosis ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-explicit-type-name"
* item.diagnosis ^extension[=].valueString = "Diagnosis"
* item.diagnosis ^requirements = "Needed to support the evaluation of the eligibility."
* item.diagnosis.diagnosis[x] 0..1 CodeableConcept or Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Condition) "Nature of illness or problem" "The nature of illness or problem in a coded form or as a reference to an external defined Condition."
* item.diagnosis.diagnosis[x] from http://hl7.org/fhir/ValueSet/icd-10 (example)
* item.diagnosis.diagnosis[x] ^requirements = "Provides health context for the evaluation of the products and/or services."
* item.diagnosis.diagnosis[x] ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* item.diagnosis.diagnosis[x] ^binding.extension.valueString = "ICD10"
* item.diagnosis.diagnosis[x] ^binding.description = "ICD10 Diagnostic codes."
* item.detail 0..* Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "Product or service details" "The plan/proposal/order describing the proposed service in detail."
* item.detail ^requirements = "Needed to provide complex service proposal such as a Device or a plan."