Resource: ImagingStudy
Id: ImagingStudy
Description: "Representation of the content produced in a DICOM imaging study. A study comprises a set of series, each of which includes a set of Service-Object Pair Instances (SOP Instances - images or other data) acquired or produced in a common context.  A series is of only one modality (e.g. X-ray, CT, MR, ultrasound), but a study may have multiple series of different modalities."
* ^meta.lastUpdated = "2023-06-14T03:32:42.153397+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Clinical.Diagnostics"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 3
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #ii
* ^status = #draft
* ^date = "2023-06-14T03:32:47.6777401+00:00"
* ^publisher = "Health Level Seven International (Imaging Integration)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/imagemgt/index.cfm"
* . ^short = "A set of images produced in single study (one or more series of references images)"
* . ^definition = "Representation of the content produced in a DICOM imaging study. A study comprises a set of series, each of which includes a set of Service-Object Pair Instances (SOP Instances - images or other data) acquired or produced in a common context.  A series is of only one modality (e.g. X-ray, CT, MR, ultrasound), but a study may have multiple series of different modalities."
* identifier 1..undefined SU Identifier "Identifiers for the whole study" "Identifiers for the ImagingStudy such as DICOM Study Instance UID, and Accession Number."
* identifier ^comment = "See discussion under [Imaging Study Implementation Notes](imagingstudy.html#notes) for encoding of DICOM Study Instance UID. Accession Number should use ACSN Identifier type."
* identifier ^requirements = "If one or more series elements are present in the ImagingStudy, then there shall be one DICOM Study UID identifier (see [DICOM PS 3.3 C.7.2](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.2.html)."
* identifier ^alias[0] = "StudyInstanceUID"
* identifier ^alias[+] = "AccessionNumber"
* status 1..1 ?! SU code "registered | available | cancelled | entered-in-error | unknown" "The current state of the ImagingStudy."
* status from http://hl7.org/fhir/ValueSet/imagingstudy-status|4.0.1 (required)
* status ^comment = "Unknown does not represent \"other\" - one of the defined statuses must apply.  Unknown is used when the authoring system is not sure what the current status is."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "ImagingStudyStatus"
* status ^binding.description = "The status of the ImagingStudy."
* modality 1..undefined SU Coding "All series modality if actual acquisition modalities" "A list of all the series.modality values that are actual acquisition modalities, i.e. those in the DICOM Context Group 29 (value set OID 1.2.840.10008.6.1.19)."
* modality from http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_29.html (extensible)
* modality ^alias[0] = "ModalitiesInStudy"
* modality ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* modality ^binding.extension.valueString = "ImagingModality"
* modality ^binding.description = "Type of acquired data in the instance."
* subject 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Device or https://fhir.kemkes.go.id/r4/StructureDefinition/Group) "Who or what is the subject of the study" "The subject, typically a patient, of the imaging study."
* subject ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-display-hint"
* subject ^extension[=].valueString = "dicom=http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.2.2.html"
* subject ^comment = "QA phantoms can be recorded with a Device; multiple subjects (such as mice) can be recorded with a Group."
* encounter undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Encounter) "Encounter with which this imaging study is associated" "The healthcare event (e.g. a patient and healthcare provider interaction) during which this ImagingStudy is made."
* encounter ^comment = "This will typically be the encounter the event occurred within, but some events may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter (e.g. pre-admission test)."
* started undefined..1 SU dateTime "When the study was started" "Date and time the study started."
* started ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-display-hint"
* started ^extension[=].valueString = "dicom=http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.2.html#sect_C.7.2.1"
* started ^alias[0] = "StudyDate"
* started ^alias[+] = "StudyTime"
* started ^example.label = "General"
* started ^example.valueDateTime = "2011-01-01T08:01:20+00:00"
* basedOn 1..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/CarePlan or https://fhir.kemkes.go.id/r4/StructureDefinition/ServiceRequest or https://fhir.kemkes.go.id/r4/StructureDefinition/Appointment or https://fhir.kemkes.go.id/r4/StructureDefinition/AppointmentResponse or https://fhir.kemkes.go.id/r4/StructureDefinition/Task) "Request fulfilled" "A list of the diagnostic requests that resulted in this imaging study being performed."
* basedOn ^requirements = "To support grouped procedures (one imaging study supporting multiple ordered procedures, e.g. chest/abdomen/pelvis CT)."
* referrer undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole) "Referring physician" "The requesting/referring physician."
* referrer ^alias[0] = "ReferringPhysiciansName"
* interpreter undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole) "Who interpreted images" "Who read the study and interpreted the images or other content."
* interpreter ^alias[0] = "Name of Physician(s) Reading Study"
* endpoint undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Endpoint) "Study access endpoint" "The network service providing access (e.g., query, view, or retrieval) for the study. See implementation notes for information about using DICOM endpoints. A study-level endpoint applies to each series in the study, unless overridden by a series-level endpoint with the same Endpoint.connectionType."
* endpoint ^comment = "Typical endpoint types include DICOM WADO-RS, which is used to retrieve DICOM instances in native or rendered (e.g., JPG, PNG), formats using a RESTful API; DICOM WADO-URI, which can similarly retrieve native or rendered instances, except using an HTTP query-based approach; DICOM QIDO-RS, which allows RESTful query for DICOM information without retrieving the actual instances; or IHE Invoke Image Display (IID), which provides standard invocation of an imaging web viewer."
* endpoint ^requirements = "Access methods for viewing (e.g., IHE’s IID profile) or retrieving (e.g., DICOM’s WADO-URI and WADO-RS) the study or the study’s series or instances. The study-level baseLocation applies to each series in the study, unless overridden in series by a series-level baseLocation of the same type."
* numberOfSeries undefined..1 SU unsignedInt "Number of Study Related Series" "Number of Series in the Study. This value given may be larger than the number of series elements this Resource contains due to resource availability, security, or other factors. This element should be present if any series elements are present."
* numberOfSeries ^alias[0] = "NumberOfStudyRelatedSeries"
* numberOfInstances undefined..1 SU unsignedInt "Number of Study Related Instances" "Number of SOP Instances in Study. This value given may be larger than the number of instance elements this resource contains due to resource availability, security, or other factors. This element should be present if any instance elements are present."
* numberOfInstances ^alias[0] = "NumberOfStudyRelatedInstances"
* procedureReference undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Procedure) "The performed Procedure reference" "The procedure which this ImagingStudy was part of."
* procedureCode undefined..undefined SU CodeableConcept "The performed procedure code" "The code for the performed procedure type."
* procedureCode from http://www.rsna.org/RadLex_Playbook.aspx (extensible)
* procedureCode ^alias[0] = "ProcedureCodeSequence"
* procedureCode ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* procedureCode ^binding.extension.valueString = "ImagingProcedureCode"
* procedureCode ^binding.description = "The performed procedure type."
* location undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Location) "Where ImagingStudy occurred" "The principal physical location where the ImagingStudy was performed."
* location ^requirements = "Ties the event to where the records are likely kept and provides context around the event occurrence (e.g. if it occurred inside or outside a dedicated healthcare setting)."
* reasonCode undefined..undefined SU CodeableConcept "Why the study was requested" "Description of clinical condition indicating why the ImagingStudy was requested."
* reasonCode from http://hl7.org/fhir/ValueSet/procedure-reason (example)
* reasonCode ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* reasonCode ^binding.extension.valueString = "ImagingReason"
* reasonCode ^binding.description = "The reason for the study."
* reasonReference undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Condition or https://fhir.kemkes.go.id/r4/StructureDefinition/Observation or https://fhir.kemkes.go.id/r4/StructureDefinition/Media or https://fhir.kemkes.go.id/r4/StructureDefinition/DiagnosticReport or https://fhir.kemkes.go.id/r4/StructureDefinition/DocumentReference) "Why was study performed" "Indicates another resource whose existence justifies this Study."
* note undefined..undefined SU Annotation "User-defined comments" "Per the recommended DICOM mapping, this element is derived from the Study Description attribute (0008,1030). Observations or findings about the imaging study should be recorded in another resource, e.g. Observation, and not in this element."
* description undefined..1 SU string "Institution-generated description" "The Imaging Manager description of the study. Institution-generated description or classification of the Study (component) performed."
* description ^alias[0] = "StudyDescription"
* series undefined..undefined SU BackboneElement "Each study has one or more series of instances" "Each study has one or more series of images or other content."
* series.uid 1..1 SU id "DICOM Series Instance UID for the series" "The DICOM Series Instance UID for the series."
* series.uid ^comment = "See [DICOM PS3.3 C.7.3](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.3.html)."
* series.uid ^requirements = "DICOM Series Instance UID."
* series.uid ^alias[0] = "SeriesInstanceUID"
* series.uid ^example.label = "General"
* series.uid ^example.valueId = "2.16.124.113543.6003.2588828330.45298.17418.2723805630"
* series.number undefined..1 SU unsignedInt "Numeric identifier of this series" "The numeric identifier of this series in the study."
* series.number ^alias[0] = "SeriesNumber"
* series.number ^example.label = "General"
* series.number ^example.valueUnsignedInt = 3
* series.modality 1..1 SU Coding "The modality of the instances in the series" "The modality of this series sequence."
* series.modality from http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_29.html (extensible)
* series.modality ^alias[0] = "Modality"
* series.modality ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* series.modality ^binding.extension.valueString = "ImagingModality"
* series.modality ^binding.description = "Type of acquired data in the instance."
* series.description undefined..1 SU string "A short human readable summary of the series" "A description of the series."
* series.description ^alias[0] = "SeriesDescription"
* series.description ^example.label = "General"
* series.description ^example.valueString = "CT Surview 180"
* series.numberOfInstances undefined..1 SU unsignedInt "Number of Series Related Instances" "Number of SOP Instances in the Study. The value given may be larger than the number of instance elements this resource contains due to resource availability, security, or other factors. This element should be present if any instance elements are present."
* series.numberOfInstances ^alias[0] = "NumberOfSeriesRelatedInstances"
* series.endpoint undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Endpoint) "Series access endpoint" "The network service providing access (e.g., query, view, or retrieval) for this series. See implementation notes for information about using DICOM endpoints. A series-level endpoint, if present, has precedence over a study-level endpoint with the same Endpoint.connectionType."
* series.endpoint ^comment = "Typical endpoint types include DICOM WADO-RS, which is used to retrieve DICOM instances in native or rendered (e.g., JPG, PNG) formats using a RESTful API; DICOM WADO-URI, which can similarly retrieve native or rendered instances, except using an HTTP query-based approach; and DICOM QIDO-RS, which allows RESTful query for DICOM information without retrieving the actual instances."
* series.endpoint ^requirements = "Access methods for retrieving (e.g., DICOM’s WADO-URI and WADO-RS) the series or the series’ instances. A baseLocation specified at the series level has precedence over a baseLocation of the same type specified at the study level."
* series.bodySite undefined..1 SU Coding "Body part examined" "The anatomic structures examined. See DICOM Part 16 Annex L (http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_L.html) for DICOM to SNOMED-CT mappings. The bodySite may indicate the laterality of body part imaged; if so, it shall be consistent with any content of ImagingStudy.series.laterality."
* series.bodySite from http://hl7.org/fhir/ValueSet/body-site (example)
* series.bodySite ^alias[0] = "BodyPartExamined"
* series.bodySite ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* series.bodySite ^binding.extension.valueString = "BodySite"
* series.bodySite ^binding.description = "Codes describing anatomical locations. May include laterality."
* series.laterality undefined..1 SU Coding "Body part laterality" "The laterality of the (possibly paired) anatomic structures examined. E.g., the left knee, both lungs, or unpaired abdomen. If present, shall be consistent with any laterality information indicated in ImagingStudy.series.bodySite."
* series.laterality from http://hl7.org/fhir/ValueSet/bodysite-laterality (example)
* series.laterality ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* series.laterality ^binding.extension.valueString = "Laterality"
* series.laterality ^binding.description = "Codes describing body site laterality (left, right, etc.)."
* series.specimen undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Specimen) "Specimen imaged" "The specimen imaged, e.g., for whole slide imaging of a biopsy."
* series.started undefined..1 SU dateTime "When the series started" "The date and time the series was started."
* series.performer undefined..undefined SU BackboneElement "Who performed the series" "Indicates who or what performed the series and how they were involved."
* series.performer ^comment = "If the person who performed the series is not known, their Organization may be recorded. A patient, or related person, may be the performer, e.g. for patient-captured images."
* series.performer ^requirements = "The performer is recorded at the series level, since each series in a study may be performed by a different performer, at different times, and using different devices. A series may be performed by multiple performers."
* series.performer ^alias[0] = "PerformingPhysicianName"
* series.performer ^alias[+] = "OperatorName"
* series.performer.function undefined..1 SU CodeableConcept "Type of performance" "Distinguishes the type of involvement of the performer in the series."
* series.performer.function from http://hl7.org/fhir/ValueSet/series-performer-function (extensible)
* series.performer.function ^requirements = "Allows disambiguation of the types of involvement of different performers."
* series.performer.function ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* series.performer.function ^binding.extension.valueString = "EventPerformerFunction"
* series.performer.function ^binding.description = "The type of involvement of the performer."
* series.performer.actor 1..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization or https://fhir.kemkes.go.id/r4/StructureDefinition/CareTeam or https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Device or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson) "Who performed the series" "Indicates who or what performed the series."
* series.instance undefined..undefined BackboneElement "A single SOP instance from the series" "A single SOP instance within the series, e.g. an image, or presentation state."
* series.instance.uid 1..1 id "DICOM SOP Instance UID" "The DICOM SOP Instance UID for this image or other DICOM content."
* series.instance.uid ^comment = "See  [DICOM PS3.3 C.12.1](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.12.html#sect_C.12.1)."
* series.instance.uid ^requirements = "DICOM SOP Instance UID."
* series.instance.uid ^alias[0] = "SOPInstanceUID"
* series.instance.uid ^example.label = "General"
* series.instance.uid ^example.valueId = "2.16.124.113543.6003.189642796.63084.16748.2599092903"
* series.instance.sopClass 1..1 Coding "DICOM class type" "DICOM instance  type."
* series.instance.sopClass from http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_B.5.html#table_B.5-1 (extensible)
* series.instance.sopClass ^alias[0] = "SOPClassUID"
* series.instance.sopClass ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* series.instance.sopClass ^binding.extension.valueString = "sopClass"
* series.instance.sopClass ^binding.description = "The sopClass for the instance."
* series.instance.number undefined..1 unsignedInt "The number of this instance in the series" "The number of instance in the series."
* series.instance.number ^alias[0] = "InstanceNumber"
* series.instance.number ^example.label = "General"
* series.instance.number ^example.valueUnsignedInt = 1
* series.instance.title undefined..1 string "Description of instance" "The description of the instance."
* series.instance.title ^comment = "Particularly for post-acquisition analytic objects, such as SR, presentation states, value mapping, etc."