Resource: List
Id: List
Description: "A list is a curated collection of resources."
* ^meta.versionId = "1"
* ^meta.lastUpdated = "2022-01-10T01:52:54.849+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Base.Management"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 1
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #not-classified
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #fhir
* ^status = #draft
* ^date = "2023-05-12T03:54:04.8907436+00:00"
* ^publisher = "Health Level Seven International (FHIR Infrastructure)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/fiwg/index.cfm"
* obeys lst-3 and lst-2 and lst-1
* . ^short = "A list is a curated collection of resources"
* . ^definition = "A list is a curated collection of resources."
* . ^alias[0] = "Collection"
* . ^alias[+] = "WorkingList"
* . ^alias[+] = "Organizer"
* identifier undefined..undefined Identifier "Business identifier" "Identifier for the List assigned for business purposes outside the context of FHIR."
* status 1..1 ?! SU code "current | retired | entered-in-error" "Indicates the current state of this list."
* status from http://hl7.org/fhir/ValueSet/list-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."
* status ^isModifierReason = "This element is labeled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "ListStatus"
* status ^binding.description = "The current state of the list."
* mode 1..1 ?! SU code "working | snapshot | changes" "How this list was prepared - whether it is a working list that is suitable for being maintained on an ongoing basis, or if it represents a snapshot of a list of items from another source, or whether it is a prepared list where items may be marked as added, modified or deleted."
* mode from http://hl7.org/fhir/ValueSet/list-mode|4.0.1 (required)
* mode ^comment = "This element is labeled as a modifier because a change list must not be misunderstood as a complete list."
* mode ^requirements = "Lists are used in various ways, and it must be known in what way it is safe to use them."
* mode ^isModifierReason = "If set to \"changes\", the list is considered incomplete, while the other two codes indicate the list is complete, which changes the understanding of the elements listed"
* mode ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* mode ^binding.extension.valueString = "ListMode"
* mode ^binding.description = "The processing mode that applies to this list."
* title undefined..1 SU string "Descriptive name for the list" "A label for the list assigned by the author."
* title ^requirements = "Allows customization beyond just the code identifying the kind of list."
* title ^example.label = "General"
* title ^example.valueString = "Dr. Jane's Patients"
* code undefined..1 SU CodeableConcept "What the purpose of this list is" "This code defines the purpose of the list - why it was created."
* code from http://hl7.org/fhir/ValueSet/list-example-codes (example)
* code ^comment = "If there is no code, the purpose of the list is implied where it is used, such as in a document section using Document.section.code."
* code ^requirements = "Lists often contain subsets of resources rather than an exhaustive list.  The code identifies what type of subset is included."
* code ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* code ^binding.extension.valueString = "ListPurpose"
* code ^binding.description = "What the purpose of a list is."
* subject undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Group or https://fhir.kemkes.go.id/r4/StructureDefinition/Device or https://fhir.kemkes.go.id/r4/StructureDefinition/Location) "If all resources have the same subject" "The common subject (or patient) of the resources that are in the list if there is one."
* subject ^comment = "Some purely arbitrary lists do not have a common subject, so this is optional."
* subject ^requirements = "The primary purpose of listing the subject explicitly is to help with finding the right list."
* encounter undefined..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Encounter) "Context in which list created" "The encounter that is the context in which this list was created."
* date undefined..1 SU dateTime "When the list was prepared" "The date that the list was prepared."
* date ^comment = "The actual important date is the date of currency of the resources that were summarized, but it is usually assumed that these are current when the preparation occurs."
* date ^requirements = "Identifies how current the list is which affects relevance."
* source undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Device) "Who and/or what defined the list contents (aka Author)" "The entity responsible for deciding what the contents of the list were. Where the list was created by a human, this is the same as the author of the list."
* source ^comment = "The primary source is the entity that made the decisions what items are in the list. This may be software or user."
* source ^requirements = "Allows follow-up as well as context."
* source ^alias[0] = "Author"
* orderedBy undefined..1 CodeableConcept "What order the list has" "What order applies to the items in the list."
* orderedBy from http://hl7.org/fhir/ValueSet/list-order (preferred)
* orderedBy ^comment = "Applications SHOULD render ordered lists in the order provided, but MAY allow users to re-order based on their own preferences as well. If there is no order specified, the order is unknown, though there may still be some order."
* orderedBy ^requirements = "Important for presentation and rendering.  Lists may be sorted to place more important information first or to group related entries."
* orderedBy ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* orderedBy ^binding.extension.valueString = "ListOrder"
* orderedBy ^binding.description = "What order applies to the items in a list."
* note undefined..undefined Annotation "Comments about the list" "Comments that apply to the overall list."
* entry undefined..undefined BackboneElement "Entries in the list" "Entries in this list."
* entry ^comment = "If there are no entries in the list, an emptyReason SHOULD be provided."
* entry ^condition = "lst-1"
* entry.flag undefined..1 CodeableConcept "Status/Workflow information about this item" "The flag allows the system constructing the list to indicate the role and significance of the item in the list."
* entry.flag from http://hl7.org/fhir/ValueSet/list-item-flag (example)
* entry.flag ^comment = "The flag can only be understood in the context of the List.code. If the flag means that the entry has actually been deleted from the list, the deleted element SHALL be true. Deleted can only be used if the List.mode is \"changes\"."
* entry.flag ^requirements = "This field is present to support various clinical uses of lists, such as a discharge summary medication list, where flags specify whether the medication was added, modified, or deleted from the list."
* entry.flag ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* entry.flag ^binding.extension.valueString = "ListItemFlag"
* entry.flag ^binding.description = "Codes that provide further information about the reason and meaning of the item in the list."
* entry.deleted undefined..1 ?! boolean "If this item is actually marked as deleted" "True if this item is marked as deleted in the list."
* entry.deleted ^comment = "If the flag means that the entry has actually been deleted from the list, the deleted element SHALL be true. Both flag and deleted can only be used if the List.mode is \"changes\". A deleted entry should be displayed in narrative as deleted.  This element is labeled as a modifier because it indicates that an item is (to be) no longer in the list."
* entry.deleted ^requirements = "The flag element may contain codes that an application processing the list does not understand. However there can be no ambiguity if a list item is actually marked as \"deleted\"."
* entry.deleted ^meaningWhenMissing = "List items are generally only treated as deleted when this element explicitly carries a value of true. Systems SHOULD always populate this value when mode is 'changes'"
* entry.deleted ^condition = "lst-2"
* entry.deleted ^isModifierReason = "If deleted is true, then the item included in the list isn't actually part of the list anymore"
* entry.date undefined..1 dateTime "When item added to list" "When this item was added to the list."
* entry.date ^requirements = "The date may be significant for understanding the meaning of items in a working list."
* entry.item 1..1 Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "Actual entry" "A reference to the actual resource from which data was derived."
* emptyReason undefined..1 CodeableConcept "Why list is empty" "If the list is empty, why the list is empty."
* emptyReason from http://hl7.org/fhir/ValueSet/list-empty-reason (preferred)
* emptyReason ^comment = "The various reasons for an empty list make a significant interpretation to its interpretation. Note that this code is for use when the entire list has been suppressed, and not for when individual items are omitted - implementers may consider using a text note or a flag on an entry in these cases."
* emptyReason ^requirements = "Allows capturing things like \"none exist\" or \"not asked\" which can be important for most lists."
* emptyReason ^condition = "lst-1"
* emptyReason ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* emptyReason ^binding.extension.valueString = "ListEmptyReason"
* emptyReason ^binding.description = "If a list is empty, why it is empty."