Resource: QuestionnaireResponse
Id: QuestionnaireResponse
Description: "A structured set of questions and their answers. The questions are ordered and grouped into coherent subsets, corresponding to the structure of the grouping of the questionnaire being responded to."
* ^meta.lastUpdated = "2022-10-05T04:55:43.9803736+00:00"
* ^extension[0].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-category"
* ^extension[=].valueString = "Clinical.Diagnostics"
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-standards-status"
* ^extension[=].valueCode = #trial-use
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-fmm"
* ^extension[=].valueInteger = 3
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-security-category"
* ^extension[=].valueCode = #patient
* ^extension[+].url = "https://fhir.kemkes.go.id/r4/StructureDefinition/structuredefinition-wg"
* ^extension[=].valueCode = #fhir
* ^date = "2023-05-12T04:00:39.3091812+00:00"
* ^publisher = "Health Level Seven International (FHIR Infrastructure)"
* ^contact[0].telecom.system = #url
* ^contact[=].telecom.value = "http://hl7.org/fhir"
* ^contact[+].telecom.system = #url
* ^contact[=].telecom.value = "http://www.hl7.org/Special/committees/fiwg/index.cfm"
* ^purpose = "To support structured, hierarchical reporting of data gathered using digital forms and other questionnaires."
* . ^short = "A structured set of questions and their answers"
* . ^definition = "A structured set of questions and their answers. The questions are ordered and grouped into coherent subsets, corresponding to the structure of the grouping of the questionnaire being responded to."
* . ^comment = "The QuestionnaireResponse contains enough information about the questions asked and their organization that it can be interpreted somewhat independently from the Questionnaire it is based on.  I.e. You don't need access to the Questionnaire in order to extract basic information from a QuestionnaireResponse."
* . ^alias[0] = "Form"
* . ^alias[+] = "QuestionnaireAnswers"
* identifier undefined..1 SU Identifier "Unique id for this set of answers" "A business identifier assigned to a particular completed (or partially completed) questionnaire."
* identifier ^requirements = "Used for tracking, registration and other business purposes."
* basedOn undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/CarePlan or https://fhir.kemkes.go.id/r4/StructureDefinition/ServiceRequest) "Request fulfilled by this QuestionnaireResponse" "The order, proposal or plan that is fulfilled in whole or in part by this QuestionnaireResponse.  For example, a ServiceRequest seeking an intake assessment or a decision support recommendation to assess for post-partum depression."
* basedOn ^requirements = "Supports traceability of responsibility for the action and allows linkage of an action to the recommendations acted upon."
* basedOn ^alias[0] = "order"
* partOf undefined..undefined SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Observation or https://fhir.kemkes.go.id/r4/StructureDefinition/Procedure) "Part of this action" "A procedure or observation that this questionnaire was performed as part of the execution of.  For example, the surgery a checklist was executed as part of."
* partOf ^comment = "Composition of questionnaire responses will be handled by the parent questionnaire having answers that reference the child questionnaire.  For relationships to referrals, and other types of requests, use basedOn."
* questionnaire undefined..1 SU Canonical(https://fhir.kemkes.go.id/r4/StructureDefinition/Questionnaire) "Form being answered" "The Questionnaire that defines and organizes the questions for which answers are being provided."
* questionnaire ^comment = "If a QuestionnaireResponse references a Questionnaire, then the QuestionnaireResponse structure must be consistent with the Questionnaire (i.e. questions must be organized into the same groups, nested questions must still be nested, etc.)."
* questionnaire ^requirements = "Needed to allow editing of the questionnaire response in a manner that enforces the constraints of the original form."
* questionnaire ^alias[0] = "Form"
* status 1..1 ?! SU code "in-progress | completed | amended | entered-in-error | stopped" "The position of the questionnaire response within its overall lifecycle."
* status from http://hl7.org/fhir/ValueSet/questionnaire-answers-status|4.0.1 (required)
* status ^comment = "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid."
* status ^requirements = "The information on Questionnaire resources  may possibly be gathered during multiple sessions and altered after considered being finished."
* status ^isModifierReason = "This element is labelled as a modifier because it is a status element that contains status entered-in-error which means that the resource should not be treated as valid"
* status ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* status ^binding.extension.valueString = "QuestionnaireResponseStatus"
* status ^binding.description = "Lifecycle status of the questionnaire response."
* subject undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "The subject of the questions" "The subject of the questionnaire response.  This could be a patient, organization, practitioner, device, etc.  This is who/what the answers apply to, but is not necessarily the source of information."
* subject ^comment = "If the Questionnaire declared a subjectType, the resource pointed to by this element must be an instance of one of the listed types."
* subject ^requirements = "Allows linking the answers to the individual the answers describe.  May also affect access control."
* subject ^alias[0] = "Patient"
* subject ^alias[+] = "Focus"
* encounter undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Encounter) "Encounter created as part of" "The Encounter during which this questionnaire response was created or to which the creation of this record is tightly associated."
* encounter ^comment = "This will typically be the encounter the event occurred within, but some activities may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter. A questionnaire that was initiated during an encounter but not fully completed during the encounter would still generally be associated with the encounter."
* encounter ^requirements = "Provides context for the information that was captured.  May also affect access control."
* authored undefined..1 SU dateTime "Date the answers were gathered" "The date and/or time that this set of answers were last changed."
* authored ^comment = "May be different from the lastUpdateTime of the resource itself, because that reflects when the data was known to the server, not when the data was captured.\n\nThis element is optional to allow for systems that might not know the value, however it SHOULD be populated if possible."
* authored ^requirements = "Clinicians need to be able to check the date that the information in the questionnaire was collected, to derive the context of the answers."
* authored ^alias[0] = "Date Created"
* authored ^alias[+] = "Date published"
* authored ^alias[+] = "Date Issued"
* authored ^alias[+] = "Date updated"
* author undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Device or https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson or https://fhir.kemkes.go.id/r4/StructureDefinition/Organization) "Person who received and recorded the answers" "Person who received the answers to the questions in the QuestionnaireResponse and recorded them in the system."
* author ^comment = "Mapping a subject's answers to multiple choice options and determining what to put in the textual answer is a matter of interpretation.  Authoring by device would indicate that some portion of the questionnaire had been auto-populated."
* author ^requirements = "Need to know who interpreted the subject's answers to the questions in the questionnaire, and selected the appropriate options for answers."
* author ^alias[0] = "Laboratory"
* author ^alias[+] = "Service"
* author ^alias[+] = "Practitioner"
* author ^alias[+] = "Department"
* author ^alias[+] = "Company"
* author ^alias[+] = "Performer"
* source undefined..1 SU Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Patient or https://fhir.kemkes.go.id/r4/StructureDefinition/Practitioner or https://fhir.kemkes.go.id/r4/StructureDefinition/PractitionerRole or https://fhir.kemkes.go.id/r4/StructureDefinition/RelatedPerson) "The person who answered the questions" "The person who answered the questions about the subject."
* source ^comment = "If not specified, no inference can be made about who provided the data."
* source ^requirements = "When answering questions about a subject that is minor, incapable of answering or an animal, another human source may answer the questions."
* item undefined..undefined BackboneElement "Groups and questions" "A group or question item from the original questionnaire for which answers are provided."
* item obeys qrs-1
* item ^comment = "Groups cannot have answers and therefore must nest directly within item. When dealing with questions, nesting must occur within each answer because some questions may have multiple answers (and the nesting occurs for each answer)."
* item.linkId 1..1 string "Pointer to specific item from Questionnaire" "The item from the Questionnaire that corresponds to this item in the QuestionnaireResponse resource."
* item.linkId ^requirements = "Items can repeat in the answers, so a direct 1..1 correspondence by position might not exist - requiring correspondence by identifier."
* item.definition undefined..1 uri "ElementDefinition - details for the item" "A reference to an [ElementDefinition](elementdefinition.html) that provides the details for the item."
* item.definition ^comment = "The ElementDefinition must be in a [StructureDefinition](structuredefinition.html#), and must have a fragment identifier that identifies the specific data element by its id (Element.id). E.g. https://fhir.kemkes.go.id/r4/StructureDefinition/Observation#Observation.value[x].\n\nThere is no need for this element if the item pointed to by the linkId has a definition listed."
* item.definition ^requirements = "A common pattern is to define a set of data elements, and then build multiple different questionnaires for different circumstances to gather the data. This element provides traceability to the common definition."
* item.text undefined..1 string "Name for group or question text" "Text that is displayed above the contents of the group or as the text of the question being answered."
* item.text ^requirements = "Allows the questionnaire response to be read without access to the questionnaire."
* item.answer undefined..undefined BackboneElement "The response(s) to the question" "The respondent's answer(s) to the question."
* item.answer ^comment = "The value is nested because we cannot have a repeating structure that has variable type."
* item.answer.value[x] undefined..1 boolean or decimal or integer or date or dateTime or time or string or uri or Attachment or Coding or Quantity or Reference(https://fhir.kemkes.go.id/r4/StructureDefinition/Resource) "Single-valued answer to the question" "The answer (or one of the answers) provided by the respondent to the question."
* item.answer.value[x] from http://hl7.org/fhir/ValueSet/questionnaire-answers (example)
* item.answer.value[x] ^comment = "More complex structures (Attachment, Resource and Quantity) will typically be limited to electronic forms that can expose an appropriate user interface to capture the components and enforce the constraints of a complex data type.  Additional complex types can be introduced through extensions. Must match the datatype specified by Questionnaire.item.type in the corresponding Questionnaire."
* item.answer.value[x] ^requirements = "Ability to retain a single-valued answer to a question."
* item.answer.value[x] ^binding.extension.url = "https://fhir.kemkes.go.id/r4/StructureDefinition/elementdefinition-bindingName"
* item.answer.value[x] ^binding.extension.valueString = "QuestionnaireAnswer"
* item.answer.value[x] ^binding.description = "Code indicating the response provided for a question."
* item.answer.item 0..* contentReference #QuestionnaireResponse.item "Nested groups and questions" "Nested groups and/or questions found within this particular answer."
* item.answer.item ^requirements = "It is useful to have \"sub-questions\", questions which normally appear when certain answers are given and which collect additional details."
* item.item 0..* contentReference #QuestionnaireResponse.item "Nested questionnaire response items" "Questions or sub-groups nested beneath a question or group."
* item.item ^requirements = "Reports can consist of complex nested groups."