CodeSystem: PrimaryCareLabParameter
Id: primary-care-lab-parameter-code
Title: "Primary Care Lab Parameter Code"
Description: "List of LOINC code used in laboratory system based on Jakarta master data"
* ^url = "http://loinc.org" 
* ^status = #active
* ^experimental = false

* include codes from system PrimaryCareLabParameter

* #88874-3 "Mycobacterium tuberculosis complex DNA [Presence] in Isolate or Specimen by Molecular genetics method"
* #89372-7 "Mycobacterium tuberculosis complex rpoB gene rifAMPin resistance mutation [Presence] by Molecular method"
* #42902-7 "Elastase.pancreatic [Presence] in Stool"
* #42902-8 "Elastase.pancreatic [Presence] in Stool"
* #10704-5 "Ova and parasites identified in Stool by Light microscopy"
* #10704-6 "Ova and parasites identified in Stool by Light microscopy"
* #10704-7 "Ova and parasites identified in Stool by Light microscopy"
* #10704-8 "Ova and parasites identified in Stool by Light microscopy"
* #10704-9 "Ova and parasites identified in Stool by Light microscopy"
* #10704-10 "Ova and parasites identified in Stool by Light microscopy"
* #10704-11 "Ova and parasites identified in Stool by Light microscopy"
* #X099193 "Bakteri"
* #X099194 "Bakteri"
* #X099195 "Bakteri"
* #X099196 "Bakteri"
* #X099197 "Bakteri"
* #41278-3 "Gross blood [Presence] of Stool Qualitative"
* #X099192 "Eritrosit feses"
* #X099187 "Pemeriksaan feses lengkap"
* #11029-6 "Consistency of Stool"
* #11029-7 "Consistency of Stool"
* #11029-8 "Consistency of Stool"
* #11029-9 "Consistency of Stool"
* #11029-10 "Consistency of Stool"
* #11029-11 "Consistency of Stool"
* #11029-12 "Consistency of Stool"
* #11029-13 "Consistency of Stool"
* #11029-14 "Consistency of Stool"
* #11029-15 "Consistency of Stool"
* #11029-16 "Consistency of Stool"
* #11029-17 "Consistency of Stool"
* #X099195 "Lain-lain"
* #2270-7 "Fat [Presence] in Stool"
* #2270-8 "Fat [Presence] in Stool"
* #42524-9 "Mucus [Presence] in Stool by Light microscopy"
* #42524-10 "Mucus [Presence] in Stool by Light microscopy"
* #51770-6 "Leukocytes [#/area] in Stool by Microscopy high power field"
	
* #17773-3 "Yeast [Presence] in Stool by Light microscopy"
* #17773-4 "Yeast [Presence] in Stool by Light microscopy"
* #2605-4 "Meat fibers [Presence] in Stool by Light microscopy"
* #55835-3 "Vegetable fibers [Presence] in Stool by Light microscopy"
* #X099194 "Sisa makanan"
* #X099195 "Sisa makanan"
* #9397-1 "Color of Stool"
* #9397-2 "Color of Stool"
* #9397-3 "Color of Stool"
* #9397-4 "Color of Stool"
* #20502-1 "Clue cells [Presence] in Vaginal fluid by Wet preparation"
* #48712-4 "Microscopic observation [Identifier] in Genital specimen by Gram stain"
* #698-1 "Neisseria gonorrhoeae [Presence] in Specimen by Organism specific culture"
* #14367-7 "Trichomonas vaginalis [Presence] in Vaginal fluid by Wet preparation"
* #14367-8 "Trichomonas vaginalis [Presence] in Vaginal fluid by Wet preparation"
* #30180-4 "Basophils/100 leukocytes in Blood"
* #706-2 "Basophils/100 leukocytes in Blood by Automated count"
* #57021-8 "CBC W Auto Differential panel - Blood"
* #26450-7 "Eosinophils/100 leukocytes in Blood"
* #713-8 "Eosinophils/100 leukocytes in Blood by Automated count"
* #26453-1 "Erythrocytes [#/volume] in Blood"
* #789-8 "Erythrocytes [#/volume] in Blood by Automated count"
* #6742-1 "Erythrocyte morphology finding [Identifier] in Blood"
* #882-1 "ABO and Rh group [Type] in Blood"
* #34530-6 "ABO and Rh group panel - Blood"
* #4544-3 "Hematocrit [Volume Fraction] of Blood by Automated count"
* #20570-8 "Hematocrit [Volume Fraction] of Blood"
* #718-7 "Hemoglobin [Mass/volume] in Blood"
* #71693-6 "Platelets reticulated/100 platelets in Blood by Automated count"
* #82477-1 "Erythrocyte sedimentation rate by Photometric method"
* #6690-2 "Leukocytes [#/volume] in Blood by Automated count"
* #26478-8 "Lymphocytes/100 leukocytes in Blood"
* #736-9 "Lymphocytes/100 leukocytes in Blood by Automated count"
* #785-6 "MCH [Entitic mass] by Automated count"
* #786-4 "MCHC [Mass/volume] by Automated count"
* #787-2 "MCV [Entitic volume] by Automated count"
* #26485-3 "Monocytes/100 leukocytes in Blood"
* #5905-5 "Monocytes/100 leukocytes in Blood by Automated count"
* #26511-6 "Neutrophils/100 leukocytes in Blood"
* #32200-8 "Segmented neutrophils/100 leukocytes in Blood by Automated count"
* #17849-1 "Reticulocytes/100 erythrocytes in Blood by Automated count"
* #777-3 "Platelets [#/volume] in Blood by Automated count"
* #3178-1 "Bleeding time by Duke method"
* #3179-9 "Bleeding time by Ivy method"
* #3183-1 "Clotting time of Blood by Lee White method"
* #75410-1 "Hepatitis B virus surface Ag [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #16935-9 "Hepatitis B virus surface Ab [Units/volume] in Serum"
* #22312-3 "Hepatitis A virus Ab [Units/volume] in Serum"
* #72376-7 "Hepatitis C virus Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #80387-4 "HIV 1+2 Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #69668-2 "HIV 1 and 2 Ab [Identifier] in Serum or Plasma by Rapid immunoassay"
* #95542-7 "SARS-CoV-2 (COVID-19) Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #87546-8 "Dengue virus IgG and IgM panel - Serum Qualitative"
* #75377-2 "Dengue virus NS1 Ag [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #23202-5 "Leptospira sp IgM Ab [Presence] in Serum"
* #17566-1 "Salmonella typhi O Ab [Presence] in Serum"
* #70569-9 "Plasmodium sp Ag [Identifier] in Blood by Rapid immunoassay"
* #5339-7 "Salmonella paratyphi A H Ab [Presence] in Serum by Latex agglutination"
* #5340-5 "Salmonella paratyphi A O Ab [Presence] in Serum by Latex agglutination"
* #5341-3 ""Salmonella paratyphi B H Ab [Presence] in Serum by Latex agglutination"
* #5342-1 ""Salmonella paratyphi B O Ab [Presence] in Serum by Latex agglutination"
* #5343-9 "Salmonella paratyphi C H Ab [Presence] in Serum by Latex agglutination"
* #5344-7 "Salmonella paratyphi C O Ab [Presence] in Serum by Latex agglutination"
* #5345-4 "Salmonella typhi H Ab [Presence] in Serum by Latex agglutination"
* #5346-2 "Salmonella typhi O Ab [Presence] in Serum by Latex agglutination"
* #97097-0 "SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay"
* #8041-6 "Treponema pallidum Ab [Presence] in Serum by Hemagglutination"
* #50690-7 "Reagin Ab [Titer] in Serum by VDRL"
* #1742-6 "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* #1744-2 "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma by No addition of P-5'-P"
* #3084-1 "Urate [Mass/volume] in Serum or Plasma"
* #1920-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* #88112-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma by No addition of P-5'-P"
* #1968-7 "Bilirubin.direct [Mass/volume] in Serum or Plasma"
* #1971-1 "Bilirubin.indirect [Mass/volume] in Serum or Plasma"
* #1975-2 "Bilirubin.total [Mass/volume] in Serum or Plasma"
* #1521-4 "Glucose [Mass/volume] in Serum or Plasma --2 hours post meal"
* #2345-7 "Glucose [Mass/volume] in Serum or Plasma"
* #41653-7 "Glucose [Mass/volume] in Capillary blood by Glucometer"
* #1558-6 "Fasting glucose [Mass/volume] in Serum or Plasma"
* #59261-8 "Hemoglobin A1c/Hemoglobin.total in Blood by IFCC protocol"
* #2085-9 "Cholesterol in HDL [Mass/volume] in Serum or Plasma"
* #2093-3 "Cholesterol [Mass/volume] in Serum or Plasma"
* #2160-0 "Creatinine [Mass/volume] in Serum or Plasma"
* #2089-1 "Cholesterol in LDL [Mass/volume] in Serum or Plasma"
* #96259-7 "Cholesterol in LDL [Mass/volume] in Serum or Plasma by Calculated by Martin-Hopkins"
* #4537-7 "Erythrocyte sedimentation rate by Westergren method"
* #20507-0 "Reagin Ab [Presence] in Serum by RPR"
* #2112-1 "Choriogonadotropin.beta subunit (pregnancy test) [Presence] in Urine"
* #2571-8 "Triglyceride [Mass/volume] in Serum or Plasma"
* #20977-5 "Urea [Mass/volume] in Blood"
* #11477-9 "Microscopic observation [Presence] in Sputum by Acid fast stain --2nd specimen"
* #3349-8 "Amphetamines [Presence] in Urine"
* #19261-7 "Amphetamines [Presence] in Urine by Screen method"
* #3390-2 "Benzodiazepines [Presence] in Urine"
* #14316-4 "Benzodiazepines [Presence] in Urine by Screen method"
* #3397-7 "Cocaine [Presence] in Urine"
* #18282-4 "Cannabinoids [Presence] in Urine by Screen method"
* #3779-6 "Methamphetamine [Presence] in Urine"
* #19554-5 "Methamphetamine [Presence] in Urine by Screen method"
* #11477-7 "Microscopic observation [Identifier] in Sputum by Acid fast stain"
* #94856-2 "Microscopic observation [Presence] in Sputum by Acid fast stain --2nd specimen"
* #13945-1 "Erythrocytes [#/area] in Urine sediment by Microscopy high power field"
* #3879-4 "Opiates [Presence] in Urine"
* #14959-1 "Microalbumin/Creatinine [Mass Ratio] in Urine"
* #1978-6 "Bilirubin.total [Mass/volume] in Urine"
* #20405-7 "Urobilinogen [Mass/volume] in Urine by Test strip"
* #20453-7 "Epithelial cells [Presence] in Urine sediment by Light microscopy"
* #20456-0 "Fungi.yeastlike [Presence] in Urine sediment by Light microscopy"
* #2349-9 "Glucose [Presence] in Urine"
* #24124-0 "Casts [Presence] in Urine sediment by Light microscopy"
* #24356-8 "Urinalysis complete panel - Urine"
* #2514-8 "Ketones [Presence] in Urine by Test strip"
* #25145-4 "Bacteria [Presence] in Urine sediment by Light microscopy"
* #25428-4 "Glucose [Presence] in Urine by Test strip"
* #2756-5 "pH of Urine"
* #2887-8 "Protein [Presence] in Urine"
* #2965-2 "Specific gravity of Urine"
* #32167-9 "Clarity of Urine"
* #32710-6 "Nitrite [Presence] in Urine"
* #5770-3 "Bilirubin.total [Presence] in Urine by Test strip"
* #5778-6 "Color of Urine"
* #5782-8 "Crystals [type] in Urine sediment by Light microscopy"
* #5787-7 "Epithelial cells [#/area] in Urine sediment by Microscopy high power field"
* #5794-3 "Hemoglobin [Presence] in Urine by Test strip"
* #5799-2 "Leukocyte esterase [Presence] in Urine by Test strip"
* #5802-4 "Nitrite [Presence] in Urine by Test strip"
* #5804-0 "Protein [Mass/volume] in Urine by Test strip"
* #5821-4 "Leukocytes [#/area] in Urine sediment by Microscopy high power field"
* #58442-5 "Other elements [Identifier] in Urine sediment by Light microscopy"
* #9439-1 "Casts [#/area] in Urine sediment by Microscopy high power field"
* #20409-9 "Erythrocytes [#/volume] in Urine by Test strip"
* #2112-1 "Choriogonadotropin.beta subunit (pregnancy test) [Presence] in Urine"
* #70144-1 "Cannabinoids [Presence] in Urine by Screen method"
* #70145-8 "Cannabinoids [Presence] in Urine by Screen method"
* #49754-5 "Epitel Squamous in Urine sediment by Light microscopy"
* #12248-1 "Epithelial cells.renal [Presence] in Urine sediment by Light microscopy"